### ISSUE TITLE
Sameboy crash with a mismatching hash error

### ISSUE THREAD

**Issue by danne2** [TASVideos/BizHawk#1009]
Sameboy can experience a crash with a mismatching hash error

```
System.InvalidOperationException: Hash did not match for heap brk-heap.  Is this the same rom with the same SyncSettings?
   at BizHawk.Emulation.Cores.Waterbox.Heap.LoadStateBinary(BinaryReader br)
   at BizHawk.Emulation.Cores.Waterbox.PeRunner.LoadStateBinary(BinaryReader br)
   at BizHawk.Emulation.Cores.Waterbox.WaterboxCore.LoadStateBinary(BinaryReader reader)
   at BizHawk.Client.Common.BinaryStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback)
   at BizHawk.Client.Common.BinaryStateLoader.GetCoreState(Action`1 callbackBinary, Action`1 callbackText)
   at BizHawk.Client.Common.SavestateManager.LoadStateFile(String path, String name)
   at BizHawk.Client.EmuHawk.MainForm.LoadState(String path, String userFriendlyStateName, Boolean fromLua, Boolean supressOSD)
   at BizHawk.Client.EmuHawk.MainForm.LoadQuickSave(String quickSlotName, Boolean fromLua, Boolean supressOSD)
   at BizHawk.Client.EmuHawk.MainForm.CheckHotkey(String trigger)
   at BizHawk.Client.EmuHawk.MainForm.<ProcessInput>b__94_0(Boolean current, String trigger)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at BizHawk.Client.EmuHawk.MainForm.ProcessInput()
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

Steps to reproduce:

Open a gameboy rom in Sameboy
Make a savestate
Swap cores
Swap back to that gameboy rom (re-loading sameboy)
Load the state.
It _should_ crash 

This occurs in the latest dev build

**Comment by hegyak** [comment]
I think the issue here is that you really shouldn't do cross-core save state loading.  Not all cores in BizHawk behave the same way.  Which will cause issues if you try and load a save state from one core, into another core.

**Comment by danne2** [comment]
You must be misunderstanding. 
You load sameboy 
Savestate
Unload sameboy (by loading another core)
Load sameboy back up
Load the savestate

This then occurs. I'm loading a sameboy savestate into sameboy.

**Comment by nattthebear** [comment]
Should be fixed.
