### ISSUE TITLE
this pops up

### ISSUE THREAD

**Issue by louisboss99** [TASVideos/BizHawk#1046]
System.Exception: Initialization of Direct3d 9 Display Method failed; falling back to GDI+ ---> System.BadImageFormatException: Could not load file or assembly 'SlimDX, Version=4.0.13.43, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format. ---> System.BadImageFormatException: Could not load file or assembly 'SlimDX, Version=4.0.13.43, Culture=neutral, PublicKeyToken=null'. This assembly was compiled for a different processor.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at BizHawk.Client.EmuHawk.Program.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9..ctor()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
   --- End of inner exception stack trace ---

**Comment by louisboss99** [comment]
System.BadImageFormatException: Could not load file or assembly 'SlimDX, Version=4.0.13.43, Culture=neutral, PublicKeyToken=null'. This assembly was compiled for a different processor.
   at BizHawk.Client.EmuHawk.KeyInput.Initialize()
   at BizHawk.Client.EmuHawk.Input.Initialize()
   at BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by Tastyfish** [comment]
This error specifically is saying that BizHawk was compiled for 32-bit and SlimDX was compiled for 64-bit or vice-versa. 

I'm assuming you're manually building BizHawk. If so, SlimDX is distributed as a 64-bit blob and BizHawk should normally be compiled to 64-bit, so I can only assume you've messed with the project settings.

Alternatively, it's somehow trying to load a SlimDX from somewhere else on your computer than the one that's in the folder.

**Comment by nattthebear** [comment]
The usual cause here is that some other dumbass program installed slimdx in the system folder or something similarly broken

**Comment by Tastyfish** [comment]
Probably
