### ISSUE TITLE
Trace Logger throws error for Genesis in current Dev Build

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1082]
Load a genesis game and try using trace logger, you'll get the following error:

System.InvalidOperationException:  is not currently supported for callbacks
   at BizHawk.Emulation.Common.MemoryCallbackSystem.Add(IMemoryCallback callback)
   at BizHawk.Emulation.Common.CallbackBasedTraceBuffer.set_Sink(ITraceSink value)
   at BizHawk.Client.EmuHawk.ToolManager.UpdateBefore()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

Trace logger works for other cores. It also works for the genesis core in 2.2.1, so something changed between then and now.

**Comment by alyosha-tas** [comment]
Ok, so CallbackBasedTraceBuffer creates a callback with scope ""
GPGX only has memory domain scope "m68K BUS"

The trace logger checks that the callback has a scope contained in the memory domain callback scopes.
Finding that "" obviously isn't in there, it throws an error.

The only obvious solution I see to this is to add "" to the memory domain scope of GPGX, which seems ugly but works and doesn't seem to harm anything, so good enough I guess.
