### ISSUE TITLE
DirectSound class not registered

### ISSUE THREAD

**Issue by Leo40Git** [TASVideos/BizHawk#1111]
Using Windows 10, developer (AppVeyor) build of commit 96fb867f9f869cef05670243b492296b90a0a399.
Error log:
```
SlimDX.DirectSound.DirectSoundException: REGDB_E_CLASSNOTREG: Class not registered (-2147221164)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.DirectSound.SoundBuffer.Play(Int32 priority, PlayFlags flags)
   at BizHawk.Client.EmuHawk.DirectSoundSoundOutput.StartSound()
   at BizHawk.Client.EmuHawk.Sound.StartSound()
   at BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)```

**Comment by Leo40Git** [comment]
Restarted my computer and it fixed itself. I guess DirectX went cross-eyed for a bit.
