### ISSUE TITLE
Please increase frame index limit for captions

### ISSUE THREAD

**Issue by greysondn** [TASVideos/BizHawk#1142]
The current limit appears to  be 1,000,000 (or perhaps one short at 999,999) I'm well aware it's high enough for pretty much every TAS, but I've alternative uses and it seems like it should be a simple fix.

![image](https://user-images.githubusercontent.com/3652901/37440566-935da4d0-27d3-11e8-8f87-335ca6068daf.png)

(The contents of that form the tail of this report)

Selecting continue gives some defaulted values.

![image](https://user-images.githubusercontent.com/3652901/37440611-beca2670-27d3-11e8-94c3-788a4d169570.png)

Which in turn leads to what appears to be an errored input in the captions list

![image](https://user-images.githubusercontent.com/3652901/37440647-ef6a1efc-27d3-11e8-9aa2-50561089e6b0.png)

Also note that in that image you can see that if I manually insert a caption (by opening the "edit captions" dialog and putting in the entire thing by hand) it works just fine.

If you need anything else from me - or need a proposed fix tested - let me know.

-----------------

Error message detail contents (trying to create a caption on frame 1040737)
```
System.ArgumentOutOfRangeException: Value of '1040737' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at BizHawk.Client.EmuHawk.SubtitleMaker.SubtitleMaker_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by alyosha-tas** [comment]
hopefully ~2 billion is enough!

**Comment by greysondn** [comment]
Give it time. Someone will do something more absurd than me with it XD

Thank you for your work <3
