### ISSUE TITLE
Scrolling down in the hex editor while viewing the System Bus in the Apple II core results in a crash

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1169]
```System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfish.Virtu.DiskIIDrive.get_IsWriteProtected()
   at Jellyfish.Virtu.DiskIIController.ReadIoRegionC0C0(Int32 address)
   at Jellyfish.Virtu.Memory.ReadIoRegionC0C0(Int32 address)
   at Jellyfish.Virtu.Memory.ReadIoRegionC0CF(Int32 address)
   at Jellyfish.Virtu.Memory.Peek(Int32 address)
   at BizHawk.Emulation.Cores.Computers.AppleII.AppleII.<SetupMemoryDomains>b__85_2(Int64 addr) in C:\Users\Daniel\Documents\BizHawk\BizHawk.Emulation.Cores\Computers\AppleII\AppleII.IMemoryDomains.cs:line 44
   at BizHawk.Client.EmuHawk.HexEditor.MakeValue(Int32 dataSize, Int64 address, Boolean& is_cheat) in C:\Users\Daniel\Documents\BizHawk\BizHawk.Client.EmuHawk\tools\HexEditor\HexEditor.cs:line 603
   at BizHawk.Client.EmuHawk.HexEditor.GenerateMemoryViewString(Boolean forWindow) in C:\Users\Daniel\Documents\BizHawk\BizHawk.Client.EmuHawk\tools\HexEditor\HexEditor.cs:line 539
   at BizHawk.Client.EmuHawk.HexEditor.UpdateValues() in C:\Users\Daniel\Documents\BizHawk\BizHawk.Client.EmuHawk\tools\HexEditor\HexEditor.cs:line 156
   at BizHawk.Client.EmuHawk.ToolManager.UpdateAfter() in C:\Users\Daniel\Documents\BizHawk\BizHawk.Client.EmuHawk\tools\ToolManager.cs:line 445
   at BizHawk.Client.EmuHawk.ToolManager.UpdateToolsAfter(Boolean fromLua) in C:\Users\Daniel\Documents\BizHawk\BizHawk.Client.EmuHawk\tools\ToolManager.cs:line 673
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force) in C:\Users\Daniel\Documents\BizHawk\BizHawk.Client.EmuHawk\MainForm.cs:line 2988
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop() in C:\Users\Daniel\Documents\BizHawk\BizHawk.Client.EmuHawk\MainForm.cs:line 483
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args) in C:\Users\Daniel\Documents\BizHawk\BizHawk.Client.EmuHawk\Program.cs:line 227```

**Comment by adelikat** [comment]
I did some investigating. It happens on the first time the address 0xC0ED is read (but only the first one).

The virtu code eventually ends up calling this property in DiskIIDrive.cs
    public bool IsWriteProtected
    {
      get
      {
        return this._disk.IsWriteProtected;
      }
    }

and _disk is currently null.  

I think some deeper digging needs to happen because i don't think it is intended that disk is null at this point, and some kind of initialization process was missed
