### ISSUE TITLE
Error starting the Application

### ISSUE THREAD

**Issue by chrdov** [TASVideos/BizHawk#1184]
Here's the details:

```
SlimDX.DirectSound.DirectSoundException: Unknown: n/a (-2004353023)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.DirectSound.SoundBuffer.Play(Int32 priority, PlayFlags flags)
   at BizHawk.Client.EmuHawk.DirectSoundSoundOutput.StartSound()
   at BizHawk.Client.EmuHawk.Sound.StartSound()
   at BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

**Comment by vadosnaprimer** [comment]
Hi.

**Comment by classicmax** [comment]
what was the problem? this page is the only search result I can find that involves the same exact error message, and I can't figure out how to fix it.

**Comment by YoshiRulz** [comment]
~~ikr, post the answer >:[~~

Try these:
* Delete/rename `config.ini`
* If you have another program that can use DirectSound e.g. Audacity, check that you can use it
* Copy a friend's config with a different sound API chosen (or manually edit the file)
* [Join IRC](https://github.com/TASVideos/BizHawk#support-and-troubleshooting) so I or whoever's awake can help you without flooding this issue
