### ISSUE TITLE
TAS Studio Crashes when loading a .tasproj file of any kind

### ISSUE THREAD

**Issue by EclipticNinja** [TASVideos/BizHawk#1201]
I got a new PC somewhat recently and transferred my .tasproj files from my old one to my new one both through an SD card and a download, both transfer methods still lead to TAS Studio crashing whenever I attempt to open them. I don't get any errors when opening old .tasproj files on the old PC.

Every time I try to open a .tasproj file from the old PC I get a dialog box that says this:
```
Unhandled exception has occurred in a component in your
application. If you click Continue, the application will ignore
this error and attempt to continue.

Value of '-10' is not valid for 'LargeChange'. 'LargeChange'
must be greater than or equal to 0.
```

There is a Details button that when clicked it says:
```
************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '-10' is not valid for 'LargeChange'. 'LargeChange' must be greater than or equal to 0.
Parameter name: LargeChange
   at System.Windows.Forms.ScrollBar.set_LargeChange(Int32 value)
   at BizHawk.Client.EmuHawk.InputRoll.RecalculateScrollBars()
   at BizHawk.Client.EmuHawk.MarkerControl.UpdateValues()
   at BizHawk.Client.EmuHawk.TAStudio.RefreshDialog(Boolean refreshTasView)
   at BizHawk.Client.EmuHawk.TAStudio.GoToFrame(Int32 frame, Boolean fromLua, Boolean fromRewinding)
   at BizHawk.Client.EmuHawk.TAStudio.LoadFile(FileInfo file, Boolean startsFromSavestate, Int32 gotoFrame)
   at BizHawk.Client.EmuHawk.TAStudio.OpenTasMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by EclipticNinja** [comment]
[This includes the .tasproj and the rom I'm using](http://www.mediafire.com/file/1cyognfsdnddnkk/TAS%20Studio%20Error.zip)

**Comment by vadosnaprimer** [comment]
Obtained the upload and removed the link, since it contains the ROM. Will check soonish.

**Comment by vadosnaprimer** [comment]
It opens perfectly in the latest release and in the latest dev build.
