### ISSUE TITLE
Savestate error. Transferred data from old version to new. tasproj load. 

### ISSUE THREAD

**Issue by chozandrias76** [TASVideos/BizHawk#1235]
`` See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

Exception Text 
System.InvalidOperationException: Internal savestate error
   at BizHawk.Emulation.Cores.Waterbox.PeRunner.LoadStateBinary(BinaryReader br)
   at BizHawk.Emulation.Cores.Nintendo.SNES.LibsnesCore.LoadStateBinary(BinaryReader reader)
   at BizHawk.Client.EmuHawk.TAStudio.LoadState(KeyValuePair`2 state)
   at BizHawk.Client.EmuHawk.TAStudio.StartAtNearestFrameAndEmulate(Int32 frame, Boolean fromLua, Boolean fromRewinding)
   at BizHawk.Client.EmuHawk.TAStudio.GoToFrame(Int32 frame, Boolean fromLua, Boolean fromRewinding)
   at BizHawk.Client.EmuHawk.TAStudio.LoadFile(FileInfo file, Boolean startsFromSavestate, Int32 gotoFrame)
   at BizHawk.Client.EmuHawk.TAStudio.OpenTasMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

 Loaded Assemblies 
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
EmuHawk
    Assembly Version: 2.0.0.13587
    Win32 Version: 2.0.0.13587
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/EmuHawk.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
BizHawk.Bizware.BizwareGL
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Bizware.BizwareGL.dll
----------------------------------------
OpenTK
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1475.5656
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/OpenTK.dll
----------------------------------------
BizHawk.Common
    Assembly Version: 2.0.0.13587
    Win32 Version: 2.0.0.13587
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Common.dll
----------------------------------------
BizHawk.Client.Common
    Assembly Version: 2.0.0.13587
    Win32 Version: 2.0.0.13587
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Client.Common.dll
----------------------------------------
BizHawk.Emulation.Common
    Assembly Version: 2.0.0.13587
    Win32 Version: 2.0.0.13587
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Emulation.Common.dll
----------------------------------------
BizHawk.Bizware.BizwareGL.OpenTK
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Bizware.BizwareGL.OpenTK.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
BizHawk.Bizware.BizwareGL.SlimDX
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Bizware.BizwareGL.SlimDX.dll
----------------------------------------
BizHawk.Bizware.BizwareGL.GdiPlus
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Bizware.BizwareGL.GdiPlus.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3.17312
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/Newtonsoft.Json.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
SlimDX
    Assembly Version: 4.0.13.43
    Win32 Version: 
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/SlimDX.dll
----------------------------------------
BizHawk.Emulation.Cores
    Assembly Version: 2.0.0.13587
    Win32 Version: 2.0.0.13587
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Emulation.Cores.dll
----------------------------------------
BizHawk.Client.ApiHawk
    Assembly Version: 0.0.0.2279
    Win32 Version: 0.0.0.2279
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Client.ApiHawk.dll
----------------------------------------
BizHawk.Emulation.DiscSystem
    Assembly Version: 2.0.0.13587
    Win32 Version: 2.0.0.13587
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Emulation.DiscSystem.dll
----------------------------------------
BizExvokeProxyAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.0.13587
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Common.dll
----------------------------------------
PeNet
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/PeNet.dll
----------------------------------------
BizInvokeProxyAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.0.13587
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/BizHawk.Common.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 1.0.6324.40785
    Win32 Version: 1.0
    CodeBase: file:///D:/Games/Emulation/Snes/Emulator/BizHawk_Developer-2018-06-28-221028-%2377bba444fdb80f0831a40a5cf4ee6b8f8ba90252/dll/ICSharpCode.SharpZipLib.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
----------------------------------------

 JIT Debugging 
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

I just downloaded the new development version of Bizhawk, hoping to see if I could boot up my old project from another version of Bizhawk. I intended to see if there was any changes to the emulator that would cause the project to desync. The above error is what was raised when I tried to load the most recent version of the project. Folders I copied over include Watch Files, and Movies.

If there is no reasonable solution to this problem, I am fine with that. I was just curious if anything could be done.

**Comment by chozandrias76** [comment]
Note: I am able to run the project without any desync errors so far.
