### ISSUE TITLE
Illegal characters in path when trying to launch game with Libretro core

### ISSUE THREAD

**Issue by PKBeam** [TASVideos/BizHawk#1357]
When I load a Libretro core (ParaLLel N64) from File > Open Advanced and try to start any game this error occurs:

> System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetExtension(String path)
   at BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args)
   at BizHawk.Client.EmuHawk.MainForm.OpenAdvancedMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by zeromus** [comment]
So stop using paths with illegal characters in it. Are you using spaces? Are you using japanese or russian characters? Only you know what weird paths youre using.

**Comment by PKBeam** [comment]
My paths are:

> D:\BizHawk\rom.z64

> D:\BizHawk\Libretro\Cores\parallel.dll

I might be badly mistaken, but I don't think any of these characters are illegal.

**Comment by vadosnaprimer** [comment]
libretro is a hack regarding quite a few cores it supports. It may be using entirely irrelevant paths without telling you which, and failing due to hardcode or something unresolved, which becomes even worse when running it from BH. You might try to debug it in VS tho.

**Comment by zeromus** [comment]
Looks like this was genuinely broken at some point for some reason having nothing to do with the libretro core specifically, likely around june of this year

**Comment by zeromus** [comment]
OK I fixed that, but parallel still just crashes. Keep in mind, probably 2/3 of all libretro cores just crash due to their general programming bugs that arent smoked out when being developed solely in the retroarch environment
