### ISSUE TITLE
A2600Hawk crashes on loading Megaboy

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1364]
Game in question: http://www.atarimania.com/game-atari-2600-vcs-megaboy_14852.html

Just crashes on loading the rom

```System.Exception: ERROR: Unable to resolve Frame. Please Report.
   at BizHawk.Emulation.Cores.Atari.Atari2600.Atari2600.FrameAdvance(IController controller, Boolean render, Boolean rendersound) in C:\Users\Daniel\Documents\bizhawk\BizHawk.Emulation.Cores\Consoles\Atari\2600\Atari2600.IEmulator.cs:line 62
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force) in C:\Users\Daniel\Documents\bizhawk\BizHawk.Client.EmuHawk\MainForm.cs:line 3000
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop() in C:\Users\Daniel\Documents\bizhawk\BizHawk.Client.EmuHawk\MainForm.cs:line 483
   at BizHawk.Client.EmuHawk.Program.Win32MainLoopCrashHandler.TryCatchFinally(String[] args) in C:\Users\Daniel\Documents\bizhawk\BizHawk.Client.EmuHawk\Program.cs:line 178```

**Comment by alyosha-tas** [comment]
Fixed I think.
Try the dev build.

**Comment by NarryG** [comment]
Same exception. Doesn't seem to have worked

**Comment by NarryG** [comment]
MD5 is B65D4A38D6047735824EE99684F3515E
It might be a bad dump. I wasn't planning on playing the game. I was just doing some testing with the files I have.

**Comment by alyosha-tas** [comment]
sha1:46977baf0e1ee6124b524258879c46f80d624fae

This is the only thing in the DB. It has the [!] with it so hopefully it's actually good. If that doesn't match your ROM maybe try to find it.

**Comment by adelikat** [comment]
MD5 is B65D4A38D6047735824EE99684F3515E
sha1:46977baf0e1ee6124b524258879c46f80d624fae
are the same ROM, you are both using the same thing, and it is marked as a good dump by BizHawk.

Using the latest master build, this game does not throw an exception for me.

**Comment by alyosha-tas** [comment]
cool, so does it work or is there another error on your end?

**Comment by alyosha-tas** [comment]
@NarryG can you double check this again so I can close this out?

**Comment by NarryG** [comment]
Whoops thought I replied. Works fine here.
