### ISSUE TITLE
Neither EmuHawk nor DiscoHawk Will Launch

### ISSUE THREAD

**Issue by emctague** [TASVideos/BizHawk#1381]
**Windows 10 build 18282 + Latest BizHawk Version**

I downloaded BizHawk onto my system today and nothing will launch:

## Symptoms in EmuHawk

EmuHawk simply launches, hangs out in my task manager for a few moments, and then terminates without any output whatsoever. I have tried running in various compatibility modes, on different GPUs, adding the DLL folder to my path, etc. #1338 might be related due to similar symptoms, but the suggested fix doesn't work.

## Symptoms in DiscoHawk

DiscoHawk launches, hangs for a few moments, and then presents me with the following output:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'BizHawk.Emulation.DiscSystem, Version=2.3.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at BizHawk.Client.DiscoHawk.Program.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at BizHawk.Client.DiscoHawk.Program.SubMain(String[] args)
   at BizHawk.Client.DiscoHawk.Program.Main(String[] args)
```

It then terminates.

I've attempted the same fixes to make this run that I tried to apply to EmuHawk and it will not function, either.

**Comment by hegyak** [comment]
This may be a low hanging fruit for a newer developer to look into possibly preventing.

**Comment by emctague** [comment]
Honestly, @hegyak, it's probably as easy as just giving a 'Quickstart' / 'How-To' on the project's homepage describing the steps needed to get the program working - simple things like ensuring the user knows to place it in a writable location (as opposed to Program Files, where I ended up placing mine to try and keep my user directories clean), etc.

**Comment by zeromus** [comment]
No, the emulator should detect running read-only and complain.
Unfortunately, I can't reproduce the problem on windows 7 with a read-only directory

**Comment by Viperision** [comment]
Hey, this is somewhat issue of mine. I've extracted the zip to C:\Users\myname\Desktop\Emulators\A - TAS. After installing bizhawk prereqs and trying to open EmuHawk.exe, two windows open one after another [https://prnt.sc/lrplhl](url) [https://prnt.sc/lrpllw](url). I'm using Windows 7 Ultimate Service Pack 1. 

Anyway, I'm quite a novice and want to use BizHawk for performing certain glitches in certain GBA (for now) games, nothing too much. Thanks for helping me in advance.

**Comment by emctague** [comment]
You should make a new issue for that

**Comment by zeromus** [comment]
Don't bother. The problem is due to some rogue program installing a slimdx.dll into your windows or program files directory. find it and delete it. then when you figure out which program is broken after deleting it, make an issue telling us which one it is, so everyone else will know what program to use. You may also file an issue with the rogue program's author telling them they should not have installed a slimdx dll in the way they did.

**Comment by YoshiRulz** [comment]
Could not reproduce exactly with 2.3.1 on Win10. If I make a copy of my clean 2.3.1 and *don't* delete `config.ini`, however, bad things happen. I'm sure there's a lot of code that assumes file writes will succeed, the one I hit was writing to saveram on closing a rom. Should this be re-opened?

**Comment by zeromus** [comment]
no, because this issue wasn't about it being read-only, it was about something else.
Don't open a new issue, either. This issue doesn't cause enough trouble to be worth worrying about
