### ISSUE TITLE
crash when right clicking genesis VDP viewer palette box

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#1449]
Title.

```
[...]
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.EmuHawk.GenVDPViewer.DrawTiles()
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
[...]
```

[The method in question](https://github.com/TASVideos/BizHawk/blob/9a5ae16c7d9adab1e774764486e6601d2bdb03ab/BizHawk.Client.EmuHawk/tools/Genesis/VDPViewer.cs#L102)

edit: stacktrace and link to code --yoshi

**Comment by alyosha-tas** [comment]
Seems like DrawTiles() in bmpViewPal_MouseClick should be UpdateValues() instead, otherwise View is null.
