### ISSUE TITLE
TAStudio Config Set max Undo Levels cause an exception: "Value was either too large or too small for an Int32"

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1555]
Default 100 undo levels are definitely not enough! So I decided to change it to much more and I entered this value 9999999999 then I got the exception:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at BizHawk.Client.EmuHawk.TAStudio.SetMaxUndoLevelsMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

SS:
![undolevelsexception](https://user-images.githubusercontent.com/49565819/56507101-cffeae00-650f-11e9-9fff-121cbb5eb67c.PNG)

This exception is similar to this one: [#1549](https://github.com/TASVideos/BizHawk/issues/1549)  I guess?

**Comment by Croopper** [comment]
It's look like that everywhere in emulator where is the possibility to enter this number is the same error.

**Comment by vadosnaprimer** [comment]
The prompt is designed to accept various things like signed int and hex, so it's the caller's job to parse it properly. Everywhere it's just assumed to be int, and anything beyond that dies. A good solution would be adding the range arguments to the prompt so it could clamp before returning, even tho it still returns a string, so it's up to a debate.
