### ISSUE TITLE
Tools tab throws exception

### ISSUE THREAD

**Issue by gnaomo** [TASVideos/BizHawk#1558]
In the tools tab, every tool throws me an exception whenever i click on it (Tool box, Lua console, Macro Tool, Virtual Pad, Multi-Disk Bundler)

This is the exception dialog:

![ToolsException](https://user-images.githubusercontent.com/38522864/56954918-56cf0e80-6b40-11e9-9162-a13544cb90e9.PNG)

Clicking details:
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at BizHawk.Client.EmuHawk.ToolManager.IsAvailable(Type t)
   at BizHawk.Client.EmuHawk.ToolManager.Load[T](String toolPath, Boolean focus)
   at BizHawk.Client.EmuHawk.MainForm.ToolBoxMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I'm using 2.3.1 x64 on a fresh unzip with prereqs installed

**Comment by YoshiRulz** [comment]
If you use Ctrl+C you can copy the contents of the exception dialog, can you edit that into your issue please?

**Comment by gnaomo** [comment]
Issue edited!

**Comment by nattthebear** [comment]
Unfortunately, the interesting stuff is probably in the LoaderExceptions here, which aren't exposed =/

**Comment by YoshiRulz** [comment]
Totally forgot about this. ~~Please try with this [custom build](https://github.com/TASVideos/BizHawk/issues/1558).~~ If you're reading this I haven't made it yet, try [the Mono branch](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/23031094/artifacts) I guess.

**Comment by zeromus** [comment]
Wild guess: try unzipping to a directory on desktop and running as administrator with your security software turned off (instead of running over a network share as a restricted user with 6 security softwares)

**Comment by gnaomo** [comment]
> 
> 
> Totally forgot about this. Please try with this [custom build](https://send.firefox.com/download/7979cbe957572e03/#nfCx91NmDJE3DvRCK0CRTQ). The extra stacktraces should be printed to stdout, so you'll need to Shift+Right-Click the background of the folder, choose "Open PowerShell window here", and run `cmd /c EmuHawk.exe`.

Done that, this time the exception dialog comes up as soon as i click the tools tab, this is what came up:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at BizHawk.Client.EmuHawk.ToolManager.IsAvailable(Type t) in C:\Users\yoshi\Desktop\bh_custom1558a\BizHawk.Client.EmuHawk\tools\ToolManager.cs:line 745
   at BizHawk.Client.EmuHawk.MainForm.ToolsSubMenu_DropDownOpened(Object sender, EventArgs e) in C:\Users\yoshi\Desktop\bh_custom1558a\BizHawk.Client.EmuHawk\MainForm.Events.cs:line 1401
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDown(Boolean mousePush)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at MenuStripEx.WndProc(Message& m) in C:\Users\yoshi\Desktop\bh_custom1558a\BizHawk.Client.EmuHawk\CustomControls\ToolStripEx.cs:line 67
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
EmuHawk
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/EmuHawk.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
BizHawk.Bizware.BizwareGL
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/BizHawk.Bizware.BizwareGL.DLL
----------------------------------------
OpenTK
    Assembly Version: 3.0.1.0
    Win32 Version: 3.0.1
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/OpenTK.DLL
----------------------------------------
BizHawk.Common
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/BizHawk.Common.DLL
----------------------------------------
BizHawk.Client.Common
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/BizHawk.Client.Common.DLL
----------------------------------------
BizHawk.Emulation.Common
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/BizHawk.Emulation.Common.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
BizHawk.Bizware.BizwareGL.OpenTK
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/BizHawk.Bizware.BizwareGL.OpenTK.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
BizHawk.Bizware.BizwareGL.SlimDX
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/BizHawk.Bizware.BizwareGL.SlimDX.DLL
----------------------------------------
BizHawk.Bizware.BizwareGL.GdiPlus
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/BizHawk.Bizware.BizwareGL.GdiPlus.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3.17312
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SlimDX
    Assembly Version: 4.0.13.43
    Win32 Version: 
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/SlimDX.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
BizHawk.Emulation.Cores
    Assembly Version: 2.3.0.0
    Win32 Version: 2.3.0.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/BizHawk.Emulation.Cores.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
BizHawk.Client.ApiHawk
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/BizHawk.Client.ApiHawk.DLL
----------------------------------------
ICSharpCode.SharpZipLib
    Assembly Version: 1.0.6324.40785
    Win32 Version: 1.0
    CodeBase: file:///C:/Users/Casa/Desktop/enrico/bizhawk/bh_custom1558a/ICSharpCode.SharpZipLib.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by YoshiRulz** [comment]
We need the ones in the PowerShell window specifically.

**Comment by gnaomo** [comment]
Nothing comes out in the powershell window

![Capture2](https://user-images.githubusercontent.com/38522864/57981457-04468b00-7a38-11e9-9553-ca2f69221d95.PNG)

**Comment by YoshiRulz** [comment]
Ok, well while I'm redoing that custom build because i stupidly deleted it, try a [dev build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/24516544/artifacts)?

**Comment by YoshiRulz** [comment]
Assuming dev build didn't help because very little has changed, here's [custom build B](https://send.firefox.com/download/d5545bd6ac2cc192/#LT0lEaIRb_wcTSBXcke0iQ) this time with [source](https://github.com/YoshiRulz/BizHawk/tree/custom1558b).

**Comment by gnaomo** [comment]
Sadly nothing comes out...
![Capture3](https://user-images.githubusercontent.com/38522864/57987426-595abf00-7a81-11e9-8a8b-4d87945299df.PNG)
![Capture4](https://user-images.githubusercontent.com/38522864/57987428-5bbd1900-7a81-11e9-8afa-2f3f3ad0f824.PNG)

**Comment by YoshiRulz** [comment]
@gnaomo, are you still experiencing this issue? If so, please try [this dev build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/28075957/artifacts) as the offending method has been rewritten.

**Comment by gnaomo** [comment]
I would like to test it out but unfortunately the pc where i experienced this issue died (out of nowhere Windows was not booting up anymore) and therefore formatted it. Now I just tested out with the latest stable release and the issue is not showing up anymore

**Comment by jdpurcell** [comment]
@gnaomo Okay thanks for the update! With that being the case and no one else having reported the same issue, I am going to close this for now.
