### ISSUE TITLE
Tools menu throwing error

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1572]
I'm getting errors in dev build after merging the rewrite to the tools isAvailable stuff. Seems to happen on all cores.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at BizHawk.Client.EmuHawk.ToolManager.IsAvailable(Type tool) in C:\Users\david\Desktop\BizHawk\BizHawk.Client.EmuHawk\tools\ToolManager.cs:line 735
   at BizHawk.Client.EmuHawk.MainForm.ToolsSubMenu_DropDownOpened(Object sender, EventArgs e) in C:\Users\david\Desktop\BizHawk\BizHawk.Client.EmuHawk\MainForm.Events.cs:line 1401
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDown(Boolean mousePush)
   at System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at MenuStripEx.WndProc(Message& m) in C:\Users\david\Desktop\BizHawk\BizHawk.Client.EmuHawk\CustomControls\ToolStripEx.cs:line 67
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by alyosha-tas** [comment]
seems to be whatever this is:

!Array.Exists(lazyAsmTypes.Value, t => t == tool)

**Comment by YoshiRulz** [comment]
"lazyAsmTypes does not contain an element that is equal to tool (method param)". Known bug in now reverted code, see #1569.
