### ISSUE TITLE
New added watch item cause unexpected error

### ISSUE THREAD

**Issue by Croopper** [TASVideos/BizHawk#1579]
It's happen when you enter too many "F" in address value. I tried to add watch item with address 0xFFD, but I passed this value "0xFFFD" then this happen:

Here there are more details for first exception:
```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: addr
   at BizHawk.Emulation.Common.MemoryDomainIntPtr.PeekByte(Int64 addr)
   at BizHawk.Emulation.Common.MemoryDomain.PeekUint(Int64 addr, Boolean bigEndian)
   at BizHawk.Client.Common.Watch.GetDWord(Boolean bypassFreeze)
   at BizHawk.Client.Common.Watch.GenerateWatch(MemoryDomain domain, Int64 address, WatchSize size, DisplayType type, Boolean bigEndian, String note, Int64 value, Int64 prev, Int32 changeCount)
   at BizHawk.Client.EmuHawk.WatchEditor.DoEdit()
   at BizHawk.Client.EmuHawk.WatchEditor.Ok_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

and the second:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at BizHawk.Client.EmuHawk.RamWatch.NewWatchMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Rather it'sn't fault of the new version, isn't it?

edit: formatting --yoshi

**Comment by YoshiRulz** [comment]
I think this should be `AddressBox.ToLong()` as [above](https://github.com/TASVideos/BizHawk/blob/e6374ef4771ff0f0b973bd5f671675269e3f7a96/BizHawk.Client.EmuHawk/tools/Watch/WatchEditor.cs#L240):
https://github.com/TASVideos/BizHawk/blob/e6374ef4771ff0f0b973bd5f671675269e3f7a96/BizHawk.Client.EmuHawk/tools/Watch/WatchEditor.cs#L310

see also #1549

**Comment by YoshiRulz** [comment]
Opening TAStudio doesn't close either the Cheats or RAM Watch window? Are you referring to after you cause this error?

**Comment by Croopper** [comment]
No, no that's not the point. I mean when you have watch window opened and you'll try to open new TAStudio window, the watch window closin' immediately but for cheats is not. It's that necessary to forcing close watch window in this case?

**Comment by alyosha-tas** [comment]
`return _domain.PeekUshort(Address % _domain.Size, BigEndian); // TODO: % size still isn't correct since it could be the last byte of the domain`

As this (misspelled) comment indicates, returning word sized data if the first byte is at the end of the domain is not protected. It does not wrap around to the start of the domain and instead tries to read past the end of the array. 

This comment is repeated in several similar places. I guess its time to clean this up.

**Comment by YoshiRulz** [comment]
Could not repro on f95bcf0e1. I can't remember if I reproduced this when I made my previous comment, or if I was just speculating.
