### ISSUE TITLE
Trace Logger crashes when scrolled to the bottom

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/BizHawk#1603]
Open BizHawk, open ROM, pause, open Trace Logger, click Logging (to window), advance a frame, scroll the log all the way to the bottom, advance another frame (or multiple frames) -> crash.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.ListView.ListViewNativeItemCollection.get_Item(Int32 displayIndex)
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at System.Windows.Forms.ListView.set_VirtualListSize(Int32 value)
   at BizHawk.Client.EmuHawk.TraceLogger.NewUpdate(ToolFormUpdateType type)
   at BizHawk.Client.EmuHawk.ToolManager.UpdateAfter()
   at BizHawk.Client.EmuHawk.ToolManager.UpdateToolsAfter(Boolean fromLua)
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

**Comment by adelikat** [comment]
I can confirm.

Tried this on C64 and SubnesHawk and both had the same crash

**Comment by alyosha-tas** [comment]
I fixed it kind of. The real issue is in some hidden class. Whatever error checking it's doing is failing. At any rate the set_VirtualListSize is doing way more then just setting an integer value.

Writing 0 first apparently resets things enough to work correctly.

**Comment by Masterjun3** [comment]
Do you think it's trying to keep the scrolling position and accessing `TopItem`, which unfortunately is null? I wasn't really able to extract an item to set it manually and check, but that's more because I'm unfamiliar with the code.

**Comment by alyosha-tas** [comment]
Maybe? It's so complicated, it's hard to tell. If i could look inside `ListViewNativeItemCollection` it might help, but I don't want to go down a bottomless pit when writing zero seems to be good enough.

**Comment by Masterjun3** [comment]
The reason I'm mentioning this is because this will be needed for reimplementing saving the scroll position which was lost in the version update from 1.11.6 -> 1.11.7.

But it's technically a different issue, so I'll open a new one.
