### ISSUE TITLE
Launching into Error window, couldn't find any of the same issue.

### ISSUE THREAD

**Issue by DarkLinkMS** [TASVideos/BizHawk#1619]
After launching EmuHawk, this exception message comes up:
SlimDX.Direct3D9.Direct3D9Exception: D3DERR_INVALIDCALL: Invalid call (-2005530516)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.Direct3D9.Texture..ctor(Device device, Int32 width, Int32 height, Int32 levelCount, Usage usage, Format format, Pool pool)
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9.CreateRenderTarget(Int32 w, Int32 h)
   at BizHawk.Client.EmuHawk.RenderTargetFrugalizer.Get(Int32 width, Int32 height)
   at BizHawk.Client.EmuHawk.DisplayManager.UpdateSourceDrawingWork(JobInfo job)
   at BizHawk.Client.EmuHawk.DisplayManager.UpdateSourceInternal(JobInfo job)
   at BizHawk.Client.EmuHawk.MainForm.Render()
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

I'm not very versed in dealing with this kind of code, so I'm sorry for my inexperience.

Edit: Re-Extracting seems to have fixed it, but I still want to know what went wrong.

**Comment by zeromus** [comment]
you changed your config > display method, or changed your GPU drivers, and in any event, your GPU drivers d3d9 support is bad. You can change DispMethod in config.ini to other values to fix that in the future
