### ISSUE TITLE
Mountain King (Atari 2600) crashes emulator

### ISSUE THREAD

**Issue by jarcen** [TASVideos/BizHawk#1628]
Latest release 2.3.2 crashes without any error message on ROM load.
Version 2.3 behaves similarly.
Version 2.2.2 shows "Unable to resolve frame. Please report."
Version 2.2.1 just hangs.
Version 2.2 is the last playable.

Master branch, though, displays this:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BizHawk.Common.ByteBuffer.set_Item(Int32 index, Byte value) in ...\BizHawk-master\BizHawk.Common\Buffer.cs:line 89
   at BizHawk.Emulation.Cores.Atari.Atari2600.mFA.WriteMem(UInt16 addr, Byte value, Boolean poke) in ...\BizHawk-master\BizHawk.Emulation.Cores\Consoles\Atari\2600\Mappers\mFA.cs:line 90
   at BizHawk.Emulation.Cores.Atari.Atari2600.mFA.WriteMemory(UInt16 addr, Byte value) in ...\BizHawk-master\BizHawk.Emulation.Cores\Consoles\Atari\2600\Mappers\mFA.cs:line 96
   at BizHawk.Emulation.Cores.Atari.Atari2600.Atari2600.WriteMemory(UInt16 addr, Byte value) in ...\BizHawk-master\BizHawk.Emulation.Cores\Consoles\Atari\2600\Atari2600.Core.cs:line 183
   at BizHawk.Emulation.Cores.Atari.Atari2600.Atari2600.CpuLink.WriteMemory(UInt16 address, Byte value) in ...\BizHawk-master\BizHawk.Emulation.Cores\Consoles\Atari\2600\Atari2600.Core.cs:line 57
   at BizHawk.Emulation.Cores.Components.M6502.MOS6502X`1.AbsIdx_WRITE_Stage5_STA() in ...\BizHawk-master\BizHawk.Emulation.Cores\CPUs\MOS 6502X\Execute.cs:line 2299
   at BizHawk.Emulation.Cores.Components.M6502.MOS6502X`1.ExecuteOneRetry() in ...\BizHawk-master\BizHawk.Emulation.Cores\CPUs\MOS 6502X\Execute.cs:line 2921
   at BizHawk.Emulation.Cores.Components.M6502.MOS6502X`1.ExecuteOne() in ...\BizHawk-master\BizHawk.Emulation.Cores\CPUs\MOS 6502X\Execute.cs:line 2983
   at BizHawk.Emulation.Cores.Atari.Atari2600.Atari2600.Cycle() in ...\BizHawk-master\BizHawk.Emulation.Cores\Consoles\Atari\2600\Atari2600.Core.cs:line 392
   at BizHawk.Emulation.Cores.Atari.Atari2600.Atari2600.FrameAdvance(IController controller, Boolean render, Boolean rendersound) in ...\BizHawk-master\BizHawk.Emulation.Cores\Consoles\Atari\2600\Atari2600.IEmulator.cs:line 50
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force) in ...\BizHawk-master\BizHawk.Client.EmuHawk\MainForm.cs:line 3025
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop() in ...\BizHawk-master\BizHawk.Client.EmuHawk\MainForm.cs:line 498
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args) in ...\BizHawk-master\BizHawk.Client.EmuHawk\Program.cs:line 233
```

**Comment by jarcen** [comment]
Found the culprit:
https://github.com/TASVideos/BizHawk/blob/dce8db231beec44ecc1ae155788fcb845f620de0/BizHawk.Emulation.Cores/Consoles/Atari/2600/Mappers/mFA.cs#L20
https://github.com/TASVideos/BizHawk/blob/dce8db231beec44ecc1ae155788fcb845f620de0/BizHawk.Emulation.Cores/Consoles/Atari/2600/Mappers/mFA.cs#L35-L40

Ram size is set incorrectly after hard reset. Don't know how it worked before, last change was 5 years ago.

**Comment by alyosha-tas** [comment]
Fixed, good catch.
