### ISSUE TITLE
emuhawk crashes upon opening 

### ISSUE THREAD

**Issue by erafgw4eg** [TASVideos/BizHawk#1651]
same error everytime. I used to play this some months ago and deleted all my old files, now when i go play new version i downloaded today this happens everytime. I tried like 5 older versions and all same thing.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Config Error ---> System.BadImageFormatException: Duplicate type with name 'System.ComponentModel.DataAnnotations' in assembly 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName)
   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetMetadataTypeAttributeType()
   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetAssociateMetadataTypeFromAttribute(Type type)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.AddValue(TKey key)
   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetAttribute[T](Type type)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.AddValue(TKey key)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at BizHawk.Client.Common.ConfigService.Load[T](String filepath)
   --- End of inner exception stack trace ---
   at BizHawk.Client.Common.ConfigService.Load[T](String filepath)
   at BizHawk.Client.Common.Config.ConfigCheckAllControlDefaults()
   at BizHawk.Client.Common.Config..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at BizHawk.Client.Common.ConfigService.Load[T](String filepath)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

edit: formatting --yoshi

**Comment by YoshiRulz** [comment]
Delete (or rename) `config.ini`.

**Comment by erafgw4eg** [comment]
i dont know where that file is im using bizhawk 2.3.2 on windows 7 64 bit

**Comment by erafgw4eg** [comment]
i tried deleting EmuHawk.exe.config but nothing changes

**Comment by YoshiRulz** [comment]
New idea: have you run the [prerequisite installer](https://github.com/TASVideos/BizHawk-Prereqs/releases/download/2.1/bizhawk_prereqs_v2.1.zip)?

**Comment by erafgw4eg** [comment]
yeah

**Comment by YoshiRulz** [comment]
My best guess is that there's a copy of `System.ComponentModel.DataAnnotations.dll` somewhere in `%PATH%`. Maybe zeromus will comment exactly where to look, until then you could always try using [a pre-generated config.ini](https://gist.githubusercontent.com/YoshiRulz/4c99638943ca12ab573b4b298c4f5b1b/raw/2d3ad44923b1797383acd849fac0dcd38b405b88/config.ini), or doing a system update and restarting.

**Comment by zeromus** [comment]
It looks like a broken .net install to me. Try uninstalling as many as you can, and installing them again

**Comment by erafgw4eg** [comment]
fixed by updating windows (only after i got the very latest updates too)
thanks for the help
