### ISSUE TITLE
Specifying "RDRAM" as the domain for event.onmemorywrite with N64 emulator returns an error

### ISSUE THREAD

**Issue by aliblong** [TASVideos/BizHawk#1733]
input: 
```lua
event.onmemorywrite(function() print(mainmemory.read_u32_be(0x1CA1D8)) end, 0x1CA1D8, "testname1", "RDRAM")
```

<details>
<summary>version 2.3.0 output</summary>

```
NLua.Exceptions.LuaException: unprotected error in call to Lua API (0)
   at NLua.Lua.PanicCallback(IntPtr luaState)
   at lua_error(lua_State* )
   at NLua.ObjectTranslator.throwError(IntPtr luaState, Object e)
   at NLua.Lua.SetPendingException(Exception e)
   at NLua.LuaMethodWrapper.call(IntPtr luaState)
   at NLua.MetaFunctions.runFunctionDelegate(IntPtr luaState)
   at lua_pcall(lua_State* , Int32 , Int32 , Int32 )
   at NLua.Lua.DoString(String chunk, String chunkName)
   at BizHawk.Client.EmuHawk.EmuLuaLibrary.ExecuteString(String command)
   at BizHawk.Client.Common.LuaSandbox.Sandbox(Action callback, Action exceptionCallback)

NLua.Exceptions.LuaException: unprotected error in call to Lua API (0)
   at NLua.Lua.PanicCallback(IntPtr luaState)
   at lua_error(lua_State* )
   at NLua.ObjectTranslator.throwError(IntPtr luaState, Object e)
   at NLua.Lua.SetPendingException(Exception e)
   at NLua.LuaMethodWrapper.call(IntPtr luaState)
   at NLua.MetaFunctions.runFunctionDelegate(IntPtr luaState)
   at lua_pcall(lua_State* , Int32 , Int32 , Int32 )
   at NLua.Lua.DoString(String chunk, String chunkName)
   at BizHawk.Client.EmuHawk.EmuLuaLibrary.ExecuteString(String command)
   at BizHawk.Client.EmuHawk.LuaConsole.<>c__DisplayClass106_0.<InputBox_KeyDown>b__2()
   at BizHawk.Client.Common.LuaSandbox.Sandbox(Action callback, Action exceptionCallback)
```

</details>

<details>
<summary>version 2.3.2 output</summary>

```
NLua.Exceptions.LuaScriptException: function

NLua.Exceptions.LuaScriptException: function
```
</details>

**Comment by YoshiRulz** [comment]
Script is malformed. 4th param of `event.onmemorywrite` is not a *domain* but a *scope*, see 1d741f3d0.

This works, though I'm not sure it will do what you expect:
```lua
event.onmemorywrite(function() print(mainmemory.read_u32_be(0x1CA1D8)) end, 0x1CA1D8, "testname1");
```
