### ISSUE TITLE
[RAM Watch] Right-clicking an empty header cell causes a crash

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/BizHawk#1745]
Affects 92b0505

Appears to be because `WatchListView.SelectedRows` in `RamWatch.cs` has a single entry of -1, which `SelectedItems` eventually tries to use as an index into the watch list.

Stacktrace:
```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at BizHawk.Client.Common.WatchList.get_Item(Int32 index) in C:\Users\yamko\source\repos\BizHawk\BizHawk.Client.Common\tools\Watch\WatchList\WatchList.cs:line 315
   at BizHawk.Client.EmuHawk.RamWatch.<get_SelectedItems>b__28_0(Int32 index) in C:\Users\yamko\source\repos\BizHawk\BizHawk.Client.EmuHawk\tools\Watch\RamWatch.cs:line 99
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at BizHawk.Client.EmuHawk.RamWatch.ListViewContextMenu_Opening(Object sender, CancelEventArgs e) in C:\Users\yamko\source\repos\BizHawk\BizHawk.Client.EmuHawk\tools\Watch\RamWatch.cs:line 1112
   at System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show(Control control, Point position)
   at System.Windows.Forms.ContextMenuStrip.ShowInternal(Control source, Point location, Boolean isKeyboardActivated)
   at System.Windows.Forms.Control.WmContextMenu(Message& m, Control sourceControl)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Zinfidel** [comment]
Resolved as of 0762b181ce5699adb311dba3d069232b6179a8d7 .
