### ISSUE TITLE
Error when opening a Lua Session

### ISSUE THREAD

**Issue by lapogne36** [TASVideos/BizHawk#1785]
When opening a Lua Session with at least 1 script, the following error message appears : 

```
Unhandled exception has occured in a component in your application. If you click Continue, the application will ignore this error and attempt to continue.

Object reference not set to an instance of an object
```

Details : 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.Common.LuaFile.Stop()
   at BizHawk.Client.EmuHawk.LuaConsole.RunLuaScripts()
   at BizHawk.Client.EmuHawk.LuaConsole.LoadSessionFromRecent(String path)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

After clicking continue, there is no script in the Lua Console. If I try to load another script, the "missing" scripts from the session will magically appear alongside the script I loaded.

Repro steps from a fresh Bizhawk : 

- Open Bizhawk
- Open the Lua Console
- Load at least 1 script
- Save the session
- Load said session

**Comment by YoshiRulz** [comment]
CNR on master. The next release of BizHawk will not be affected by this bug.
