### ISSUE TITLE
System.Exception: Initialization of Direct3d 9 Display Method failed

### ISSUE THREAD

**Issue by RMMaxX** [TASVideos/BizHawk#1827]
Idk what happened, but after the MSVC 2012 error i got this.

The actual error:
System.Exception: Initialization of Direct3d 9 Display Method failed; falling back to GDI+ ---> System.BadImageFormatException: Could not load file or assembly 'SlimDX, Version=4.0.13.43, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format. ---> System.BadImageFormatException: Could not load file or assembly 'SlimDX, Version=4.0.13.43, Culture=neutral, PublicKeyToken=null'. This assembly was compiled for a different processor.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at BizHawk.Client.EmuHawk.Program.CurrentDomain_AssemblyResolve(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   --- End of inner exception stack trace ---
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9..ctor()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
   --- End of inner exception stack trace ---

Please help me

**Comment by YoshiRulz** [comment]
> This assembly was compiled for a different processor.

Are you using a 32-bit version of Windows? BizHawk is for 64-bit processors only.

**Comment by RMMaxX** [comment]
my life is a lie

**Comment by RMMaxX** [comment]
thank you btw........have a fantastic day......

**Comment by Spikestuff** [comment]
@RMMaxX as a note, The 1.X.X versions of Hawk are for 32bit processors. However it isn't supported anymore.
