### ISSUE TITLE
Bizhawk crash on startup

### ISSUE THREAD

**Issue by EvilThorn** [TASVideos/BizHawk#1849]
Out of nowhere, bizhawk crashes with this error:

SlimDX.DirectInput.DirectInputException: E_FAIL: An undetermined error occurred (-2147467259)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.DirectInput.DirectInput..ctor()
   at BizHawk.Client.EmuHawk.KeyInput.Initialize()
   at BizHawk.Client.EmuHawk.Input.Initialize()
   at BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   at BizHawk.Client.EmuHawk.Program.Win32MainLoopCrashHandler.TryCatchFinally(String[] args)
No clue why because it was working the other day.

I assumed it was because my version is outdated, but the latest version does the same exact thing, have no idea whats causing this.

**Comment by Spikestuff** [comment]
Is it similar to: #1424

**Comment by EvilThorn** [comment]
I dont remember selecting OpenGL in bizhawk, but if i did, i dont know why its messing up a fresh install too.

**Comment by EvilThorn** [comment]
after a restart, everything suddenly fixed itself, i assume it was a direct input issue.
