### ISSUE TITLE
Exception in Lua forms button click

### ISSUE THREAD

**Issue by brunovalads** [TASVideos/BizHawk#1957]
### Issue
When I try to click a button in a **second form** opened by a lua script, it throws an exception in the click event. It used to work fine on version 2.3.2 and prior, the issue started on 2.3.3 and still the same with the latest dev build c8ae659b (2020.04.28). Also, the issue happens in both Lua cores.

### How to reproduce
1. Load the script below:
```lua
local Form = {}

function Form.form_test1()

  Form.form1 = forms.newform(200, 100, "1")
  
  forms.button(Form.form1, "PRINT 1", function() print("Button in window 1 works! ".. os.clock()) end, 2, 2, 75, 24)
  
  forms.button(Form.form1, "Window 2", Form.form_test2, 2, 30, 100, 24)
end

function Form.form_test2()
  
  Form.form2 = forms.newform(200, 200, "2")
  
  forms.button(Form.form2, "PRINT 2", function() print("Button in window 2 works! ".. os.clock()) end, 2, 2, 75, 24)
end

print("\nScript loaded!")

Form.form_test1()
```
2. Click the "Window 2" button to open the second form;
3. Click "PRINT 2" button.

### Output error
The error after clicking the button is the following (translated):
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.EmuHawk.LuaWinform.DoLuaEvent(IntPtr handle)
   at BizHawk.Client.EmuHawk.LuaButton.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
[Full log here](https://pastebin.com/2QpKDtnu)

### Working scenario
In version 2.3.2 for instance, the script should print in the console the following messages when clicking the "PRINT" buttons respectively:
```
Button in window 1 works!
Button in window 2 works!
```

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

**Comment by brunovalads** [comment]
After 16 different builds, i was able to narrow down the issue to one commit: d757b8e64f2c7a356ad9e92e96ca3b688e32e713 by @adelikat, i hope this helps.

**Comment by brunovalads** [comment]
Just to confirm: it's working as intended now. Thanks!
