### ISSUE TITLE
uzebox unhandled exception on load

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2022]
Seems like `public static SystemInfo RunningSystem` is null?

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.EmuHawk.ClientApi.OnRomLoaded(IEmulator emu) in C:\Develop\BizHawk\src\BizHawk.Client.EmuHawk\Api\ClientApi.cs:line 220
   at BizHawk.Client.EmuHawk.MainForm.LoadRomInternal(String path, LoadRomArgs args) in C:\Develop\BizHawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 3800
   at BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args) in C:\Develop\BizHawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 3536
   at BizHawk.Client.EmuHawk.MainForm.LoadRomFromRecent(String rom) in C:\Develop\BizHawk\src\BizHawk.Client.EmuHawk\MainForm.cs:line 1979
   at BizHawk.Client.EmuHawk.ToolExtensions.ToolExtensions.<>c__DisplayClass0_1.<RecentMenu>b__3(Object o, EventArgs ev) in C:\Develop\BizHawk\src\BizHawk.Client.EmuHawk\Extensions\ToolExtensions.cs:line 58
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by nattthebear** [comment]
Same shit in pcfx

**Comment by YoshiRulz** [comment]
Is this something that can be bisected for?

**Comment by nattthebear** [comment]
To clarify:  You can choose to click through the exception, and if you do the emulator seems to function normally.  Maybe that adjusts the prio.

**Comment by adelikat** [comment]
No, it's neglect.  This is ApiHawk, and it has its own lists of things.  When it started affecting Rom loading is when it started getting integrated into things
