### ISSUE TITLE
TAStudio: Importing movies from bk2 broken in Dev build

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2060]
Repro: importing any .bk2 into TAStudio throws a null reference exception.

**Comment by YoshiRulz** [comment]
`Bk2Movie.Emulator` is null when execution reaches here:
https://github.com/TASVideos/BizHawk/blob/59baedbc644ec5759b56e9a7a7baca0e9d2aa727/src/BizHawk.Client.Common/movie/bk2/Bk2Movie.cs#L60

Stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.Common.Bk2Movie.LogGeneratorInstance(IController source) in /mnt/c/Users/groom/source/repos/BizHawk/src/BizHawk.Client.Common/movie/bk2/Bk2Movie.cs:line 62
   at BizHawk.Client.Common.Bk2Movie.AppendFrame(IController source) in /mnt/c/Users/groom/source/repos/BizHawk/src/BizHawk.Client.Common/movie/bk2/Bk2Movie.cs:line 94
   at BizHawk.Client.Common.MovieConversionExtensions.MovieConversionExtensions.ToTasMovie(IMovie old) in /mnt/c/Users/groom/source/repos/BizHawk/src/BizHawk.Client.Common/movie/conversions/MovieConversionExtensions.cs:line 45
   at BizHawk.Client.Common.MovieSession.ConvertToTasProj() in /mnt/c/Users/groom/source/repos/BizHawk/src/BizHawk.Client.Common/movie/MovieSession.cs:line 373
   at BizHawk.Client.EmuHawk.TAStudio.ConvertCurrentMovieToTasproj() in /mnt/c/Users/groom/source/repos/BizHawk/src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.cs:line 612
   at BizHawk.Client.EmuHawk.TAStudio.OpenTasMenuItem_Click(Object sender, EventArgs e) in /mnt/c/Users/groom/source/repos/BizHawk/src/BizHawk.Client.EmuHawk/tools/TAStudio/TAStudio.MenuItems.cs:line 125
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by alyosha-tas** [comment]
This issue was fixed in Dev build at some point.
