### ISSUE TITLE
BizHawk crashes when trying to load a savestate made with different sync settings

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2090]
Create a savestate with GB or PSX, then change some core settings and reboot the core. Then, if you try to load that savestate, you get this for Gambatte:
```
System.InvalidOperationException: Save buffer size mismatch!
   at BizHawk.Emulation.Cores.Sony.PSX.Octoshock.LoadStateBinary(BinaryReader reader)
   at BizHawk.Client.Common.BinaryStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback)
   at BizHawk.Client.Common.BinaryStateLoader.GetCoreState(Action`1 callbackBinary, Action`1 callbackText)
   at BizHawk.Client.Common.SavestateManager.LoadStateFile(IEmulator emulator, String path)
   at BizHawk.Client.EmuHawk.MainForm.LoadState(String path, String userFriendlyStateName, Boolean fromLua, Boolean suppressOSD)
   at BizHawk.Client.EmuHawk.MainForm.LoadQuickSave(String quickSlotName, Boolean fromLua, Boolean suppressOSD)
   at BizHawk.Client.EmuHawk.MainForm.CheckHotkey(String trigger)
   at BizHawk.Client.EmuHawk.MainForm.<ProcessInput>b__101_0(Boolean current, String trigger)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at BizHawk.Client.EmuHawk.MainForm.ProcessInput()
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```
And this for Octoshock:
```
System.InvalidOperationException: Savestate buffer size mismatch!
   at BizHawk.Emulation.Cores.Nintendo.Gameboy.Gameboy.LoadStateBinary(BinaryReader reader)
   at BizHawk.Client.Common.BinaryStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback)
   at BizHawk.Client.Common.BinaryStateLoader.GetCoreState(Action`1 callbackBinary, Action`1 callbackText)
   at BizHawk.Client.Common.SavestateManager.LoadStateFile(IEmulator emulator, String path)
   at BizHawk.Client.EmuHawk.MainForm.LoadState(String path, String userFriendlyStateName, Boolean fromLua, Boolean suppressOSD)
   at BizHawk.Client.EmuHawk.MainForm.LoadQuickSave(String quickSlotName, Boolean fromLua, Boolean suppressOSD)
   at BizHawk.Client.EmuHawk.MainForm.CheckHotkey(String trigger)
   at BizHawk.Client.EmuHawk.MainForm.<ProcessInput>b__101_0(Boolean current, String trigger)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at BizHawk.Client.EmuHawk.MainForm.ProcessInput()
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```
Also, after closing the error window, the BizHawk process ends instantly without updating settings.ini.

First, BizHawk shouldn't close abruptly after displaying the error window.
Second, the error window should explain which are the sync settings that are different between the savestate that was attempted to load and the currently set ones for the running core.

**Comment by YoshiRulz** [comment]
A possibly related crash from Discord:
![screencap](https://cdn.discordapp.com/attachments/280813077853765632/765761244509634580/unknown.png)
It's partially cut off and in Norwegian(?), but the stacktrace is from jumping to a marker TAStudio. Something like:
```
InvalidOperationException: Save buffer size mismatch!
  at BizHawk.Emulation.Cores.Sony.PSX.Octoshock.LoadStateBinary
  at BizHawk.Client.EmuHawk.TAStudio.LoadState
  at BizHawk.Client.EmuHawk.TAStudio.StartAtNearestFrameAndEmulate
  at BizHawk.Client.EmuHawk.TAStudio.GoToFrame
  at BizHawk.Client.EmuHawk.MarkerControl.MarkerView_MouseDoubleClick
```

**Comment by CasualPokePlayer** [comment]
> Also, after closing the error window, the BizHawk process ends instantly without updating settings.ini.

This doesn't seem to be the case anymore.

> Second, the error window should explain which are the sync settings that are different between the savestate that was attempted to load and the currently set ones for the running core.

Sync Settings aren't stated. The error here will occur for any unexpected state size difference (which *can* be due to sync settings). For Gambatte it would be GB/SGB vs GBC/GBA, as their state sizes differ (GB/SGB has less VRAM and less WRAM than GBC/GBA). Perhaps the error message could just mention it might be the issue. Or maybe sync settings should be stated for comparision purposes?

**Comment by YoshiRulz** [comment]
EmuHawk will also crash if you manually load a state made with a different core. The cause is the same—a complete lack of checks (due to lack of metadata in the state which could be checked, and no the filename doesn't count), so I'll group it with this issue.

<details>
<summary>Genplus-gx state in SMSHawk</summary>
```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
  at System.IO.BinaryReader.ReadByte () [0x00018] in <65a38edf81fe405bb4fb28e56b25f9d8>:0 
  at BizHawk.Common.Util.ReadByteBuffer (System.IO.BinaryReader br, System.Boolean returnNull) [0x00039] in <c328af811283451bad98d1ea7b521f6d>:0 
  at BizHawk.Common.Serializer.Sync (System.String name, System.UInt16[]& val, System.Boolean useNull) [0x00024] in <c328af811283451bad98d1ea7b521f6d>:0 
  at BizHawk.Emulation.Cores.Components.Z80A.Z80A`1[TLink].SyncState (BizHawk.Common.Serializer ser) [0x0000d] in <1bb6a1dd97e34bb49f3752922835cdef>:0 
  at BizHawk.Emulation.Cores.Sega.MasterSystem.SMS.SyncState (BizHawk.Common.Serializer ser) [0x0003c] in <1bb6a1dd97e34bb49f3752922835cdef>:0 
  at BizHawk.Emulation.Common.StateSerializer.LoadStateBinary (System.IO.BinaryReader br) [0x0000d] in <b672afc98bb04de793936de43c0d9d21>:0 
  at BizHawk.Client.Common.SavestateFile+<>c__DisplayClass8_0.<Load>b__6 (System.IO.BinaryReader br) [0x00000] in <114f106be390452bb60283b4ba542864>:0 
  at BizHawk.Client.Common.ZipStateLoader+<>c__DisplayClass13_0.<GetLump>b__0 (System.IO.Stream s, System.Int64 _) [0x0000c] in <114f106be390452bb60283b4ba542864>:0 
  at BizHawk.Client.Common.ZipStateLoader.GetLump (BizHawk.Client.Common.BinaryStateLump lump, System.Boolean abort, System.Action`2[T1,T2] callback, System.Boolean isZstdCompressed) [0x00051] in <114f106be390452bb60283b4ba542864>:0 
  at BizHawk.Client.Common.ZipStateLoader.GetLump (BizHawk.Client.Common.BinaryStateLump lump, System.Boolean abort, System.Action`1[T] callback) [0x0000d] in <114f106be390452bb60283b4ba542864>:0 
  at BizHawk.Client.Common.ZipStateLoader.GetCoreState (System.Action`1[T] callbackBinary, System.Action`1[T] callbackText) [0x00007] in <114f106be390452bb60283b4ba542864>:0 
  at BizHawk.Client.Common.SavestateFile.Load (System.String path, BizHawk.Client.Common.IDialogParent dialogParent) [0x000e6] in <114f106be390452bb60283b4ba542864>:0 
  at BizHawk.Client.EmuHawk.MainForm.LoadState (System.String path, System.String userFriendlyStateName, System.Boolean suppressOSD) [0x00051] in <660e8e0d19e64f7fbd44787eca24f9bb>:0 
  at (wrapper remoting-invoke-with-check) BizHawk.Client.EmuHawk.MainForm.LoadState(string,string,bool)
  at BizHawk.Client.EmuHawk.MainForm.LoadStateAs () [0x0007f] in <660e8e0d19e64f7fbd44787eca24f9bb>:0 
  at BizHawk.Client.EmuHawk.MainForm.LoadNamedStateMenuItem_Click (System.Object sender, System.EventArgs e) [0x00000] in <660e8e0d19e64f7fbd44787eca24f9bb>:0
```
</details>

<details>
<summary>new BSNES state in Snes9x</summary>
```
System.InvalidOperationException: Waterbox Error: Bad hash for state
  at BizHawk.Emulation.Cores.Waterbox.WaterboxHostNative+ReturnData.GetDataOrThrow () [0x00028] in <1a3b94fc22d848e7a49d5eed9d4faf14>:0 
  at BizHawk.Emulation.Cores.Waterbox.WaterboxHost.LoadStateBinary (System.IO.BinaryReader br) [0x0002a] in <1a3b94fc22d848e7a49d5eed9d4faf14>:0 
  at BizHawk.Emulation.Cores.Waterbox.WaterboxCore.LoadStateBinary (System.IO.BinaryReader reader) [0x0000c] in <1a3b94fc22d848e7a49d5eed9d4faf14>:0 
  at BizHawk.Client.Common.SavestateFile+<>c__DisplayClass8_0.<Load>b__6 (System.IO.BinaryReader br) [0x00000] in <e1eb19a9e5624fe989b6081465a13632>:0 
  at BizHawk.Client.Common.ZipStateLoader+<>c__DisplayClass13_0.<GetLump>b__0 (System.IO.Stream s, System.Int64 _) [0x0000c] in <e1eb19a9e5624fe989b6081465a13632>:0 
  at BizHawk.Client.Common.ZipStateLoader.GetLump (BizHawk.Client.Common.BinaryStateLump lump, System.Boolean abort, System.Action`2[T1,T2] callback, System.Boolean isZstdCompressed) [0x00043] in <e1eb19a9e5624fe989b6081465a13632>:0 
  at BizHawk.Client.Common.ZipStateLoader.GetLump (BizHawk.Client.Common.BinaryStateLump lump, System.Boolean abort, System.Action`1[T] callback) [0x0000d] in <e1eb19a9e5624fe989b6081465a13632>:0 
  at BizHawk.Client.Common.ZipStateLoader.GetCoreState (System.Action`1[T] callbackBinary, System.Action`1[T] callbackText) [0x00006] in <e1eb19a9e5624fe989b6081465a13632>:0 
  at BizHawk.Client.Common.SavestateFile.Load (System.String path, BizHawk.Client.Common.IDialogParent dialogParent) [0x000b6] in <e1eb19a9e5624fe989b6081465a13632>:0 
  at BizHawk.Client.EmuHawk.MainForm.LoadState (System.String path, System.String userFriendlyStateName, System.Boolean suppressOSD) [0x0003c] in <d66adcbf582e48bcb8ed2509e844be1d>:0 
  at (wrapper remoting-invoke-with-check) BizHawk.Client.EmuHawk.MainForm.LoadState(string,string,bool)
  at BizHawk.Client.EmuHawk.MainForm.LoadStateAs () [0x00060] in <d66adcbf582e48bcb8ed2509e844be1d>:0 
  at BizHawk.Client.EmuHawk.MainForm.LoadNamedStateMenuItem_Click (System.Object sender, System.EventArgs e) [0x00000] in <d66adcbf582e48bcb8ed2509e844be1d>:0
```
</details>
