### ISSUE TITLE
After using BizHawk 2.4.1 normally since release, no version of BizHawk opens now due to a DirectSound error.

### ISSUE THREAD

**Issue by Acumenium** [TASVideos/BizHawk#2123]
SlimDX.DirectSound.DirectSoundException: E_FAIL: An undetermined error occurred (-2147467259)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.DirectSound.SoundBuffer.Play(Int32 priority, PlayFlags flags)
   at BizHawk.Client.EmuHawk.DirectSoundSoundOutput.StartSound()
   at BizHawk.Client.EmuHawk.Sound.StartSound()
   at BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

What exactly is going on here? I also can't run other emulators properly either---provided Sound is enabled. VBA-M goes from 100% speed to 25% speed if Sound is on, for instance.

**Comment by YoshiRulz** [comment]
Has your hardware changed? DirectSound bugs tend to go away upon reboot. You can get BizHawk to load by editing `config.ini`—find the line containing `SoundOutputMethod` and change it to `"SoundOutputMethod": 2,`.

**Comment by Acumenium** [comment]
Have rebooted several times. Hardware hasn't changed. Still using the same laptop I was when it was working fine.

It's loading now. Thank you! What exactly went wrong here? Did a setting corrupt?

**Comment by YoshiRulz** [comment]
DirectSound is just the default on Windows. The edit is equivalent to choosing `Config` > `Sound...` > `Output Method` > `OpenAL` in EmuHawk and restarting it.
