### ISSUE TITLE
retroizer crash

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2158]
When trying to load supplied retroizer shader I crash, tried multiple systems Win 7 and 10, tried direct3d and ogl

`===================
Pass 0:
Vertex Shader:
 System.InvalidOperationException: Error compiling shader: G:\emuups\BizHawk_Developer-2020-06-20 AppVeyor 0.0.0.4979 Win 64 bit 007 Complete\memory(85,22): error X3000: syntax error: unexpected token '['
 ---> SlimDX.CompilationException: G:\emuups\BizHawk_Developer-2020-06-20 AppVeyor 0.0.0.4979 Win 64 bit 007 Complete\memory(85,22): error X3000: syntax error: unexpected token '['
 ---> SlimDX.Direct3D9.Direct3D9Exception: E_FAIL: An undetermined error occurred (-2147467259)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Object dataKey, Object dataValue)
   at SlimDX.CompilationException.Check[T](Int32 hr, String errors)
   --- End of inner exception stack trace ---
   at SlimDX.Direct3D9.ShaderBytecode.Compile(Byte[] sourceData, Macro[] defines, Include includeFile, String functionName, String profile, ShaderFlags flags, String& errors)
   at BizHawk.Client.EmuHawk.IGL_SlimDX9.CreateVertexShader(String source, String entry, Boolean required)
   --- End of inner exception stack trace ---
   at BizHawk.Client.EmuHawk.IGL_SlimDX9.CreateVertexShader(String source, String entry, Boolean required) 
-------
Fragment Shader:
System.InvalidOperationException: Error compiling shader: (85): error X3000: syntax error: unexpected token '['
 ---> SlimDX.CompilationException: (85): error X3000: syntax error: unexpected token '['
 ---> SlimDX.Direct3D9.Direct3D9Exception: E_FAIL: An undetermined error occurred (-2147467259)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Object dataKey, Object dataValue)
   at SlimDX.CompilationException.Check[T](Int32 hr, String errors)
   --- End of inner exception stack trace ---
   at SlimDX.Direct3D9.ShaderBytecode.Compile(Byte[] sourceData, Macro[] defines, Include includeFile, String functionName, String profile, ShaderFlags flags, String& errors)
   at BizHawk.Client.EmuHawk.IGL_SlimDX9.CreateFragmentShader(String source, String entry, Boolean required)
   --- End of inner exception stack trace ---
   at BizHawk.Client.EmuHawk.IGL_SlimDX9.CreateFragmentShader(String source, String entry, Boolean required)
`

**Comment by zeromus** [comment]
fixed by 703a51be0948d635f499f44713def12de984b693
