### ISSUE TITLE
Exception when adjusting tilt control in Virtual Pad

### ISSUE THREAD

**Issue by shenef** [TASVideos/BizHawk#2352]
### Summary
The sliders in the Virtual Pad seem to be linked which can cause the Light Sensor slider to go negative or above 255 when moving a Tilt Control slider.
Moving only the Light Sensor slider causes the Tilt Control sliders to move but throws no exception.

### Repro
1. load GBA ROM
2. open Virtual Pad
3. move a Tilt Control slider to the left or quickly to the right

### Output
Moving to the left:
```
System.ArgumentOutOfRangeException: Value of '-357' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.TrackBar.set_Value(Int32 value)
   at BizHawk.Client.EmuHawk.VirtualPadAnalogButton.RefreshWidgets()
   at BizHawk.Client.EmuHawk.VirtualPadAnalogButton.UpdateValues()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at BizHawk.Client.EmuHawk.VirtualpadTool.UpdateAfter()
   at BizHawk.Client.EmuHawk.ToolManager.UpdateToolsAfter()
   at BizHawk.Client.EmuHawk.MainForm.UpdateToolsAfter()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

Moving to the right: 
```
System.ArgumentOutOfRangeException: Value of '712' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.TrackBar.set_Value(Int32 value)
   at BizHawk.Client.EmuHawk.VirtualPadAnalogButton.RefreshWidgets()
   at BizHawk.Client.EmuHawk.VirtualPadAnalogButton.UpdateValues()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at BizHawk.Client.EmuHawk.VirtualpadTool.UpdateAfter()
   at BizHawk.Client.EmuHawk.ToolManager.UpdateToolsAfter()
   at BizHawk.Client.EmuHawk.MainForm.UpdateToolsAfter()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

### Host env.
- BizHawk dev build 0.0.0.5445; Win10 Home 2004; Intel/NVIDIA

**Comment by adelikat** [comment]
Fixed
