### ISSUE TITLE
Yabause Error involving OpenGL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#236]
```
What steps will reproduce the problem?
1. Open a Saturn Game with OpenGL mode set to true.
2. Reboot the core.
3. Error

What is the expected output? What do you see instead?
A core accepted the rom, but threw an exception while loading it:
System.Exception: libyabause_init() failed!
   at BizHawk.Emulation.Cores.Sega.Saturn.Yabause.Init(Byte[] bios)
   at BizHawk.Emulation.Cores.Sega.Saturn.Yabause..ctor(CoreComm CoreComm, Disc CD, Object SyncSettings)
   at BizHawk.Client.Common.RomLoader.LoadRom(String path, CoreComm nextComm, Boolean forceAccurateCore)

What version of the product are you using? On what operating system?
SVN r7470

Other things?
Software Rendering does not have this error.  It only applies to OpenGL mode.
```

Original issue reported on code.google.com by `hegyak` on 1 Aug 2014 at 2:17

**Comment by hegyak** [comment]
Resolved.
