### ISSUE TITLE
Alternate Sync causes FFmpeg dumping to crash for N64

### ISSUE THREAD

**Issue by Zinfidel** [TASVideos/BizHawk#2376]
### Summary
Dumping N64 video while using the Alternate Sync option causes FFmpeg to crash shortly after starting the dump. I have tested this only with Star Wars Episode 1 Racer for the N64. I tested Pink Panther: Pinkadelic Pursuit for GBA, and the bug did not manifest for that core/game. I tried changing the throttling option to Audio Throttling (I *think* this setting is related somehow to what alternate sync does) but it did not change the crash.

### Repro
1. Load `Star Wars Episode I - Racer (U) [!]`
1. Pause the emulator
1. File > AVI/WAV > Config and Record
1. Check Alternate Sync
1. Choose FFmpeg writer and click OK
1. Choose MP4 profile (the crash happens for any profile I choose)
1. Choose a place to save the file
1. Unpause the emulator
1. Wait a moment (usually about 5 seconds for me)

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.Exception: A/V Desync?
   at BizHawk.Client.EmuHawk.NutMuxer.WriteAudioFrame(Int16[] samples)
   at BizHawk.Client.EmuHawk.NutMuxer.Finish()
   at BizHawk.Client.EmuHawk.FFmpegWriter.CloseFileSegment()
   at BizHawk.Client.EmuHawk.FFmpegWriter.Dispose()
   at BizHawk.Client.EmuHawk.MainForm.AbortAv()
   at BizHawk.Client.EmuHawk.MainForm.AvFrameAdvance()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

![HOnIWpessY](https://user-images.githubusercontent.com/1929934/92312467-a6fc8300-ef75-11ea-8bd3-72ab25e1fa31.png)
![EyLEDT33Og](https://user-images.githubusercontent.com/1929934/92312470-a9f77380-ef75-11ea-9b70-9e3a2a3a3513.png)

### Host env.
- BizHawk 2.4.0; Win10 Home; Intel
- BizHawk 2.4.2; Win10 Home; Intel
- BizHawk 2.5.0; Win10 Home; Intel

**Comment by Zinfidel** [comment]
Probably related to this: #2137

**Comment by nattthebear** [comment]
More or less the same as https://github.com/TASVideos/BizHawk/issues/133, and probably other bugs I can't find.  BizHawk assumes that the number of audio samples returned by an emulation core each frame has at least some connection to reality, but Mupen does not obey this.  Alternate sync helps dumps not sound like arse, but it has its limits.

**Comment by nattthebear** [comment]
Note that #2137, while a nice thing to add, won't really fix this well because for that proposal, the number of audio samples emitted by the core each frame is trusted as an authority, where as in mupen it is not.
