### ISSUE TITLE
Failed to convert file to Bizhawk 2.5

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#2476]
1) Download the .gmv file from http://tasvideos.org/1774S.html
2) Import into Bizhawk 2.5 with the proper game loaded.
3) Try to load the resulting .bkm file

Result: An exception is thrown. The movie fails to run. You can also first try to save as a .bk2 using Bizhawk 2.4.1, but you will get the same problem.

```

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BizHawk.Client.Common.MovieSession.QueueNewMovie(IMovie movie, Boolean record, String systemId, IDictionary`2 preferredCores)
   at BizHawk.Client.EmuHawk.MainForm.StartNewMovie(IMovie movie, Boolean record)
   at BizHawk.Client.EmuHawk.PlayMovie.Run()
   at BizHawk.Client.EmuHawk.PlayMovie.Ok_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


```

**Comment by YoshiRulz** [comment]
This affects all BizHawk movies which:
* do not have an entry with the key `Core` in their header, such as those made by the `.gmv` importer; and
* are played back on any version after 56e3642d5 (which includes 2.5, 2.5.1, and 2.5.2 releases).

**Comment by nattthebear** [comment]
Thanks for the bisect

**Comment by nattthebear** [comment]
It also has to be for a system where we only have one core, I think.
ebf0f6685edc146458fbcd080a6141167a124c5a
