### ISSUE TITLE
RAM Search crashes when deleting addresses

### ISSUE THREAD

**Issue by Tompala** [TASVideos/BizHawk#2572]
Done on Biz 2.5.2, this method would not have crashed on 2.4.2

There are several steps to do this, here is one that works consistently:

1. Open a GBC game.
2. Open RAM Search
3. Mark address 0000 to 5908 (Random number, works with several)
4. Remove selected
5.  Crash

Also happens on other systems, when deleting other addresses etc.
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at BizHawk.Client.Common.RamSearchEngine.RamSearchEngine.get_Item(Int32 index)
   at BizHawk.Client.EmuHawk.RamSearch.ListView_QueryItemBkColor(Int32 index, RollColumn column, Color& color)
   at BizHawk.Client.EmuHawk.InputRoll.DoBackGroundCallback(List`1 visibleColumns, Rectangle rect, Int32 firstVisibleRow, Int32 lastVisibleRow)
   at BizHawk.Client.EmuHawk.InputRoll.DrawBg(List`1 visibleColumns, Rectangle rect, Int32 firstVisibleRow, Int32 lastVisibleRow)
   at BizHawk.Client.EmuHawk.InputRoll.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by alyosha-tas** [comment]
Can repro., it looks like the problem is that with anything more then ~half the addresses removed the scroll bar attempts to end up past the end of the data.

**Comment by Tompala** [comment]
Should have added that this can happen even if you have very few addresses left. Every time I've gone down to four addresses, only removing with the "Search" option up to this point, then when I delete one of the remaining addresses, it will also crash.

**Comment by alyosha-tas** [comment]
I tried just now and cannot repro with this new method, so I think it's solved.
