### ISSUE TITLE
Enabling Single Instance Mode causes exception/crash

### ISSUE THREAD

**Issue by koitsu** [TASVideos/BizHawk#2601]
### Summary
When Single Instance Mode is enabled (GUI: Config -> Customize -> General -> Startup Options -> Single instance mode, `config.ini`: `SingleInstanceMode` value `true`), BizHawk 2.6.2 crashes on startup.

This is a regression from 2.4.0, where the feature worked fine.

### Repro
See Summary

### Output
```
System.InvalidOperationException: window title can only be changed by calling UpdateWindowTitle (which calls WindowTitle getter)
   at BizHawk.Client.EmuHawk.FormBase.set_Text(String value)
   at BizHawk.Client.EmuHawk.Program.SingleInstanceController.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run(String[] commandLine)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

### Host env.
- BizHawk 2.6.2: Windows 7 Ultimate x64 SP1, Intel/NVIDIA

**Comment by nattthebear** [comment]
https://github.com/TASVideos/BizHawk/issues/2577

**Comment by YoshiRulz** [comment]
There's no 2.6.2 (yet). Did you mean 2.5.2 or 2.6? Either way this bug is no longer present.

**Comment by koitsu** [comment]
I'm sorry.  Yes, I meant BizHawk 2.6.

I additionally apologise for this ticket.  I did search GitHub Issues for `is:issue SingleInstanceMode`, erroneously assuming someone would have mentioned the config.ini variable name, and found no results.  I wasn't aware of #2577 until now.

Thank you.
