### ISSUE TITLE
BizHawk Load Error

### ISSUE THREAD

**Issue by Dandaman955** [TASVideos/BizHawk#2660]
Hello, I'm running into a problem while running GemFire (Mega Drive ROM, US region) with BizHawk. I've tested other Mega Drive ROMs beforehand and they seem to work fine, and I've converted the ROM from smd->bin and found another ROM with the same results. This is the error message:

```
---------------------------
load error
---------------------------
A core accepted the rom, but threw an exception while loading it:

System.ArgumentException: Illegal characters in path.

   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)

   at System.IO.Path.GetExtension(String path)

   at BizHawk.Common.HawkFile.<>c__DisplayClass36_0.<BindByExtensionCore>b__1(HawkArchiveFileItem item)

   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at BizHawk.Common.HawkFile.BindByExtensionCore(Boolean first, String[] extensions)

   at BizHawk.Client.Common.RomLoader.HandleArchiveBinding(HawkFile file)

   at BizHawk.Client.Common.RomLoader.LoadRom(String path, CoreComm nextComm, String launchLibretroCore, String forcedCoreName, Int32 recursiveCount)
---------------------------
OK   
---------------------------

```
I'm not too sure what the problem is: Judging by the error log, there are illegal characters in the path, but it is in the same folder as the rest of the ROMs, and the folder that contains the ROM as well as the ROM itself, are both named 'GemFire' and 'GemFire.smd', respectively. Does anyone know what's the matter?

**Comment by YoshiRulz** [comment]
Duplicate of #2587? Switch to release 2.6.1, or as a workaround, put the rom in a `.zip` and load that.

**Comment by Dandaman955** [comment]
Brilliant, thank you.
