### ISSUE TITLE
event.onmemoryexecuteany doesn't work for N64 games

### ISSUE THREAD

**Issue by MrCheeze** [TASVideos/BizHawk#2808]
### Summary
I'm trying to hook some lua code to run after every instruction in a N64 game, but get an error every time. ~~I'm pretty sure this worked in some past releases~~, and it still works with other cores.

### Repro
Load a N64 rom
Run this lua code: `event.onmemoryexecuteany(function() end)`

### Output
```
NLua.Exceptions.LuaException: unprotected error in call to Lua API (0)
   at NLua.Lua.PanicCallback(IntPtr luaState)
   at lua_error(lua_State* )
   at NLua.ObjectTranslator.throwError(IntPtr luaState, Object e)
   at NLua.Lua.SetPendingException(Exception e)
   at NLua.LuaMethodWrapper.call(IntPtr luaState)
   at NLua.MetaFunctions.runFunctionDelegate(IntPtr luaState)
   at lua_resume(lua_State* , Int32 )
   at BizHawk.Client.EmuHawk.Win32LuaLibraries.ResumeScript(LuaFile lf)
   at BizHawk.Client.EmuHawk.LuaConsole.<>c__DisplayClass61_1.<ResumeScripts>b__1()
   at BizHawk.Client.Common.LuaSandbox.Sandbox(Action callback, Action exceptionCallback)
```

Also, afterwards when closing the lua window, this log appears:
```
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at BizHawk.Emulation.Cores.Nintendo.N64.NativeApi.mupen64plusApi.RemoveBreakpoint(BreakType type, Nullable`1 address)
   at BizHawk.Emulation.Cores.Nintendo.N64.N64.RemoveBreakpoint(IMemoryCallback callback)
   at BizHawk.Emulation.Common.MemoryCallbackSystem.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1.Remove(T item)
   at BizHawk.Emulation.Common.MemoryCallbackSystem.RemoveInternal(MemoryCallbackDelegate action)
   at BizHawk.Emulation.Common.MemoryCallbackSystem.RemoveAll(IEnumerable`1 actions)
   at BizHawk.Client.Common.LuaFunctionList.Clear(IEmulator emulator)
   at BizHawk.Client.EmuHawk.Win32LuaLibraries.Close()
   at BizHawk.Client.EmuHawk.LuaConsole.<.ctor>b__26_0(Object o, CancelEventArgs e)
   at System.Windows.Forms.Form.OnClosing(CancelEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Host env.
- BizHawk 2.6.2 or the latest dev build, Windows 10

**Comment by MrCheeze** [comment]
A correction - this has never worked. I must have been thinking of another of the related functions.
