### ISSUE TITLE
SNES Super Scope gives an exeption error

### ISSUE THREAD

**Issue by ozderya** [TASVideos/BizHawk#2856]
I don't remember which core I was using. I change my second controller to Super Scope and now I cant open any SNES games. BizHawk trows me an error and got closed.

Core: 2.6.2

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at BizHawk.Emulation.Cores.Nintendo.BSNES.BsnesSuperScopeController.UpdateState(IController controller)
   at BizHawk.Emulation.Cores.Nintendo.BSNES.BsnesControllers.CoreInputPoll(IController controller)
   at Bizhawk.BizInvokeProxyBsnesCoreImpl.snes_run()
   at BizHawk.Emulation.Cores.Nintendo.BSNES.BsnesCore.FrameAdvance(IController controller, Boolean render, Boolean renderSound)
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

**Comment by YoshiRulz** [comment]
The stacktrace is for the new BSNES. Specifically here, where the array in question has indices 0..3, but the loop is over 2..5:
https://github.com/TASVideos/BizHawk/blob/58293dde9f0aec3aff59ecce433a0e81b6f0672a/src/BizHawk.Emulation.Cores/Consoles/Nintendo/BSNES/BsnesControllers.cs#L273-L287
