### ISSUE TITLE
[snes] gameshark and gamegenie codes don't work with the codeconverter. What codes  do and how the hell do you use the thing if it's just broken?

### ISSUE THREAD

**Issue by gorxk** [TASVideos/BizHawk#2863]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
[//]: # "Briefly describe what's broken. Include relevant details: loaded core, loaded rom's hash, open tools, running scripts... You can embed a screenshot if it's easier to show the bug, but if you need more than one please put them at the end."
Whenever my cat sits on the left side of my keyboard, games run too fast for me to react to.

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. first step
2. second step
3. et cetera

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.InvalidOperationException: o noes
  at BizHawk.Client.EmuHawk.HawkBiz.Crash()
  at BizHawk.Client.EmuHawk.HawkBiz.RunWithoutCrashing()
```

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"
- BizHawk 2.5.2; Win10 Pro 1903; AMD/AMD
- BizHawk 2.4.2; Win8.1; Intel/NVIDIA
- BizHawk dev build at 370996875; Win10 Home 1809; Intel/AMD
- BizHawk 2.5; Fedora 31; AMD/NVIDIA

[//]: # "(screenshots, if applicable)"

[//]: # "That's it! If you'd like to help more, you could try a dev build (see Testing in the readme) or an older release. Click submit now and you can edit it later."

BLUF: code converter has a hissy fit saying all codes must start with a 0 or 1.  While all of the codes listed here: https://www.almarsguides.com/retro/walkthroughs/snes/games/MegaManX/ProActionReplay/ work in snes9x standalone and mesen-s and retroach.  none of the codes in that linked website, and many of the ones on gameshacking.org either. Where do I find ones that do work?

**Comment by CasualPokePlayer** [comment]
https://prnt.sc/1cbk1f7

Actual error given for putting these codes into some SNES games. Cheat Converter seems to be assuming these are Game Boy GS codes? (is this some SGB bs?)

**Comment by gorxk** [comment]
That's the error ! And gameshark codes from gamehacking codes give me the
same error.

**Comment by YoshiRulz** [comment]
Looks like `GbGameSharkDecoder` replaced `SnesActionReplayDecoder` in https://github.com/TASVideos/BizHawk/pull/1867/commits/d0db4188d37cb8cbb3afe8a7428d3708b185f0cb, part of #1867. @adelikat
