### ISSUE TITLE
Malformed Movie Input will Crash EmuHawk

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#298]
```
What steps will reproduce the problem?
1. Open Gun.Smoke (NES)
2. Open the Movie File I attached.
3. Watch the crash

What is the expected output? What do you see instead?
Error appears around 70 Frames.

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BizHawk.Client.Common.Bk2ControllerAdapter.SetControllersAsMnemonic(String mnemonic)
   at BizHawk.Client.Common.Bk2Movie.GetInputState(Int32 frame)
   at BizHawk.Client.Common.MovieSession.LatchInputFromLog()
   at BizHawk.Client.Common.MovieSession.HandleMovieOnFrameLoop()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

StackTrace:
   at BizHawk.Client.Common.Bk2ControllerAdapter.SetControllersAsMnemonic(String mnemonic)
   at BizHawk.Client.Common.Bk2Movie.GetInputState(Int32 frame)
   at BizHawk.Client.Common.MovieSession.LatchInputFromLog()
   at BizHawk.Client.Common.MovieSession.HandleMovieOnFrameLoop()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)


What version of the product are you using? On what operating system?
r8093

Please provide any additional information below.
I did this intentionally.  This should NOT and will not happen normally.

```

Original issue reported on code.google.com by `hegyak` on 21 Oct 2014 at 4:22

Attachments:
- [Gun.Smoke.bk2](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-298/comment-0/Gun.Smoke.bk2)

**Comment by adelikat** [comment]
I think crashing is acceptable behavior here.  The movie in question has a line filled with pipes.  There's no end to the amount of scenarios an app could encounter when receiving data.  This is a manufactured scenario that can't be caused by bizhawk, or any reasonable human attempt.  It is expected to break, I don't believe in the idea that expected break scenarios should never close the app.
