### ISSUE TITLE
TAStudio will Eat Input

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/bizhawk#442]
```
What steps will reproduce the problem?
1. Record a Movie using TAStudio.  Virtu is required to be used.
2. Save your TASProj.
3. Close EmuHawk.
4. Open EmuHawk again.
5. Open the Same ROM for Virtu.
6. Open TAStudio from the Tools Dropdown.
7. default.tasproj will be created.
8. Open your TASProj
9. The following message will appear:
"Tastudio could not open the file. Due to the loading process, the 
emulator/Tastudio may be in an unspecified state depending on the error.
The movie will load.
9. Close TAStudio.  Make sure EmuHawk is paused.
10. Attempt to Close EmuHawk.  When asked if you want to save, Yes or No will 
cause the error.
11. EmuHawk will give this error,

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an 
object.
   at System.Windows.Forms.ToolStripProgressBar.set_Value(Int32 value)
   at BizHawk.Client.EmuHawk.TAStudio.<InitializeSaveWorker>b__3(Object s, ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnProgressChanged(ProgressChangedEventArgs e)
   at System.ComponentModel.BackgroundWorker.ProgressReporter(Object arg)
   at System.ComponentModel.BackgroundWorker.ReportProgress(Int32 percentProgress, Object userState)
   at System.ComponentModel.BackgroundWorker.ReportProgress(Int32 percentProgress)
   at BizHawk.Client.Common.TasMovie.Write(String fn)
   at BizHawk.Client.Common.Bk2Movie.Stop(Boolean saveChanges)
   at BizHawk.Client.EmuHawk.MainForm.<.ctor>b__d(Object o, CancelEventArgs e)
   at System.Windows.Forms.Form.OnClosing(CancelEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at BizHawk.Client.EmuHawk.MainForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

The TASProj file only has a header file in it now.  Your work has been lost.

12. Unpause EmuHawk.  This error appears:
System.NullReferenceException: Object reference not set to an instance of an 
object.
   at BizHawk.Client.Common.TasMovie.RecordFrame(Int32 frame, IController source)
   at BizHawk.Client.Common.MovieSession.HandleFrameLoopForRecordMode()
   at BizHawk.Client.Common.MovieSession.HandleMovieOnFrameLoop()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

StackTrace:
   at BizHawk.Client.Common.TasMovie.RecordFrame(Int32 frame, IController source)
   at BizHawk.Client.Common.MovieSession.HandleFrameLoopForRecordMode()
   at BizHawk.Client.Common.MovieSession.HandleMovieOnFrameLoop()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

EmuHawk will close afterward.

Note that using Open Movie dialog box does NOT cause this error.  Only the 
above instructions cause this issue.  It only appears to effect the Virtu Core. 
 Also Opening TAStudio in any other core, then Virtu, will also cause this 
error.
```

Original issue reported on code.google.com by `hegyak` on 19 Jun 2015 at 7:51

**Comment by hegyak** [comment]
This has been corrected.
