### ISSUE TITLE
New System.OutOfMemoryException

### ISSUE THREAD

**Issue by mouse1093** [TASVideos/BizHawk#514]
So same general issue as before, TASing DK64 from a savestate and about 450-500 frames in, I crash. This time the exception was uncaught:
```

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BizHawk.Client.EmuHawk.TAStudio.LoadState(KeyValuePair`2 state)
   at BizHawk.Client.EmuHawk.TAStudio.StartAtNearestFrameAndEmulate(Int32 frame)
   at BizHawk.Client.EmuHawk.TAStudio.GoToFrame(Int32 frame)
   at BizHawk.Client.EmuHawk.TAStudio.TasView_PointedCellChanged(Object sender, CellEventArgs e)
   at BizHawk.Client.EmuHawk.InputRoll.CellChanged(Cell newCell)
   at BizHawk.Client.EmuHawk.InputRoll.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by vadosnaprimer** [comment]
This happens to me as a System.IO.EndOfStreamException with the same stack when starting states get erased according to capacity and I try to access state at frame 0. Will investigate.
