### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by Drflash55** [TASVideos/BizHawk#520]
I got an error when trying to start a new project from selected frame when I already started a new project from said selected frame.

http://puu.sh/kLzAj/f6cf6e7452.txt

Posted a link here due to how big report was.

**Comment by Drflash55** [comment]
Here's the bug report in no file format...

`System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary``2.Insert(TKey key, TValue value, Boolean add)
   at BizHawk.Client.Common.MovieConversionExtensions.MovieConversionExtensions.ConvertToSavestateAnchoredMovie(TasMovie old, Int32 frame, Byte[] savestate)
   at BizHawk.Client.EmuHawk.TAStudio.StartNewProjectFromNowMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

Does anyone know why this happens?
