### ISSUE TITLE
IndexOutOfRangeException in SNES Graphics Debugger

### ISSUE THREAD

**Issue by Neui** [TASVideos/BizHawk#529]
When viewing the BGs in the SNES Graphics Debugger, go to the first black (invalid) tile either at the bottom-left or on the right-bottom.

It doesn't crash or so and it would happen rarely for a (normal) user, so it isn't so important.

    System.IndexOutOfRangeException: Index was outside the bounds of the array.
       at BizHawk.Client.EmuHawk.SNESGraphicsDebugger.UpdateViewerMouseover(Point loc)
       at BizHawk.Client.EmuHawk.SNESGraphicsDebugger.viewer_MouseMove(Object sender, MouseEventArgs e)
       at System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
       at System.Windows.Forms.Control.WmMouseMove(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

See the following animation if instructions unclear: \([Link](http://puu.sh/kVYoT/c56b48628b.gif)\)
![Animation demonstrating how to do it](http://puu.sh/kVYoT/c56b48628b.gif)

**Comment by zeromus** [comment]
thanks for tracking that down so precisely
