### ISSUE TITLE
Opening the same movie that is already opened with TAStudio

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#532]
->Profil: N64 TAS
->Do a random movie with TAStudio
->Save as "X"
->Open X

Where X is the name of the movie.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at BizHawk.Client.Common.TasStateManager.Load(BinaryReader br)
   at BizHawk.Client.Common.TasMovie.<Load>b__41(BinaryReader br, Int64 length)
   at BizHawk.Client.Common.BinaryStateLoader.<>c__DisplayClass4.<GetLump>b__3(Stream s, Int64 length)
   at BizHawk.Client.Common.BinaryStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback)
   at BizHawk.Client.Common.BinaryStateLoader.GetLump(BinaryStateLump lump, Boolean abort, Action`2 callback)
   at BizHawk.Client.Common.TasMovie.Load(Boolean preload)
   at BizHawk.Client.Common.MovieSession.QueueNewMovie(IMovie movie, Boolean record, IEmulator emulator)
   at BizHawk.Client.EmuHawk.MainForm.StartNewMovie(IMovie movie, Boolean record)
   at BizHawk.Client.EmuHawk.TAStudio.StartNewMovieWrapper(Boolean record, IMovie movie)
   at BizHawk.Client.EmuHawk.TAStudio.HandleMovieLoadStuff(TasMovie movie)
   at BizHawk.Client.EmuHawk.TAStudio.LoadFile(FileInfo file)
   at BizHawk.Client.EmuHawk.TAStudio.OpenTasMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I can click continue, and retry and it gives the same error.

**Comment by zeromus** [comment]
cant repro, i assume it has been fixed since last release.
