### ISSUE TITLE
Error with TAStudio:

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#533]
************** Exception Text **************
System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToSingle(String value)
   at BizHawk.Client.EmuHawk.TAStudio.TasView_KeyDown(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at BizHawk.Client.EmuHawk.InputRoll.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

STEPS:
->Open a N64 ROM
->Open TAStudio
->Double click on a square column of the column "aX"
->Press "-".

It should throw "System.FormatException: Input string was not in a correct format.".

EDIT: Woops, forgot to add an important detail to the title. I should've added: pressing "-" on a aX column.

**Comment by Niamek** [comment]
An another note, it's exclusive to N64 I think(since you need to be able to input from your keyboard some value, like the aX and aY)

**Comment by vadosnaprimer** [comment]
I confirm, but I don't understand what float logic is trying to do there, so I can't really fix it. Requires SuuperW.
