### ISSUE TITLE
BasicBot: Fatal error (Object reference not set to an instance of an object)

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#602]
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at BizHawk.Client.EmuHawk.BasicBot.Update(Boolean fast)
>    at BizHawk.Client.EmuHawk.BasicBot.UpdateValues()
>    at BizHawk.Client.EmuHawk.ToolManager.UpdateBefore()
>    at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
>    at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
>    at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

Hot to do:
->Open a GBA ROM
->Open Basic Bot
->Put anything in the addresses and controls sections so that you can't get a "best"(in other word, always get "attemp:0".
--------->Example: 03A3 after 100 frames only, some stuffs in the controls section.
->Stop the bot
->Play the best "attempt".

It should make a fatal exception and the emulator will be closed by itself.

**Comment by Niamek** [comment]
I keep getting different errors of "Object reference not set to an instance of an object."

Is there a way to understand a little bit where the error could come from with the exceptions? If I could understand a little bit these, I could be better with repro steps.
