### ISSUE TITLE
Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by Drflash55** [TASVideos/BizHawk#633]
Here's the error I'm getting with the recent stable version of BizHawk when using TAStudio.

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at BizHawk.Client.Common.TasStateManager.ExcludeStates()
   at BizHawk.Client.Common.TasStateManager.Save(BinaryWriter bw)
   at BizHawk.Client.Common.TasMovie.<Write>b__20(BinaryWriter bw)
   at BizHawk.Client.Common.BinaryStateSaver.<>c__DisplayClass1.<PutLump>b__0(Stream s)
   at BizHawk.Client.Common.IonicZipWriter.WriteItem(String name, Action`1 callback)
   at BizHawk.Client.Common.BinaryStateSaver.PutLump(BinaryStateLump lump, Action`1 callback)
   at BizHawk.Client.Common.TasMovie.Write(String fn)
   at BizHawk.Client.Common.Bk2Movie.Save()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

Don't know how it happens...

**Comment by vadosnaprimer** [comment]
Can you try interim?
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by adelikat** [comment]
Since it is probably fixed and the original poster hasn't responded in some months, I am closing this ticket.  It can be reopened if someone confirms that the issues has not bee resolved.

**Comment by Drflash55** [comment]
Haven't used TAStudio in a while...

When I get the time, and when I'm doing projects, that I run into this again, I will ask for this to be re-opened.
