### ISSUE TITLE
Random crashes from TASstudio

### ISSUE THREAD

**Issue by jmarvins** [TASVideos/BizHawk#664]
Without an apparent pattern, TASstudio crashes on me quite often.  I have noticed this happening on trying to load a save state, on advancing frames, on searching, and so forth.  Here is its report, always of the same type.

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.SortedList`2.GetByIndex(Int32 index)
   at System.Collections.Generic.SortedList`2.ValueList.get_Item(Int32 index)
   at BizHawk.Client.Common.TasStateManager.StateToRemove()
   at BizHawk.Client.Common.TasStateManager.MaybeRemoveStates()
   at BizHawk.Client.Common.TasStateManager.SetState(Int32 frame, Byte[] state, Boolean skipRemoval)
   at BizHawk.Client.Common.TasStateManager.Capture(Boolean force)
   at BizHawk.Client.Common.TasMovie.GreenzoneCurrentFrame()
   at BizHawk.Client.Common.MovieSession.HandleMovieAfterFrameLoop()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

Now, I have no idea what this has to do with anything.  Have I set something up improperly?

**Comment by vadosnaprimer** [comment]
Are you using the interim build?
http://tasvideos.org/forum/viewtopic.php?p=333074#333074

**Comment by jmarvins** [comment]
All I did was install the latest windows binary release of BizHawk.  If that includes the interim build, then yes, otherwise no.

**Comment by vadosnaprimer** [comment]
It doesn't, I fix a shitload of stuff in interims, use one.

**Comment by jmarvins** [comment]
I just grabbed it; thanks for letting me know.

**Comment by jmarvins** [comment]
Switched to interim and haven't seen this error yet, but now I am seeing a new and strange issue: when I enter input for a frame, it either disappears after one frame (while still having its effect) or it doubles/triples.  Is this a known issue?

**Comment by vadosnaprimer** [comment]
I haven't heard of such a thing. Are you entering input by drawing?

**Comment by jmarvins** [comment]
No, either using keyboard or the on-screen input pad.

**Comment by vadosnaprimer** [comment]
Then I think this hasn't been thoroughly tested. But drawing is faster. As well as navigating by mouse wheel with the right button held down (advancing/rewinding).

**Comment by jmarvins** [comment]
Thanks, I'll give it a shot.  Note that I'm doing this with an N64 game, if that's relevant.

**Comment by vadosnaprimer** [comment]
While testing Perfect Dark, I also had a situation where input recorded into a normal movie wasn't visible in tastudio... This stuff is deeply broken.

**Comment by vadosnaprimer** [comment]
Can you try your bugs in the newest build?
https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts
