### ISSUE TITLE
System.InvalidOperationException: Error compiling shader:

### ISSUE THREAD

**Issue by PrinceP** [TASVideos/BizHawk#667]
System.InvalidOperationException: Error compiling shader:  ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SlimDX.Utilities.BufferToString(ID3DXBuffer\* buffer)
   at SlimDX.Direct3D9.ShaderBytecode.Compile(Byte[] sourceData, Macro[] defines, Include includeFile, String functionName, String profile, ShaderFlags flags, String& errors)
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9.CreateFragmentShader(Boolean cg, String source, String entry, Boolean required)
   --- End of inner exception stack trace ---
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9.CreateFragmentShader(Boolean cg, String source, String entry, Boolean required)
   at BizHawk.Bizware.BizwareGL.GuiRenderer..ctor(IGL owner)
   at BizHawk.Client.EmuHawk.DisplayManager..ctor(PresentationPanel presentationPanel)
   at BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

Windows 10
BizHawk-1.11.6

**Comment by zeromus** [comment]
This was either fixed at some point, or is a driver bug too awful for us to fix. We've fixed it several times in several different forms in slimdx. I think this is fixed unless I hear otherwise.
