### ISSUE TITLE
NullReferenceException makes it impossible to record movies on Libretro cores

### ISSUE THREAD

**Issue by Fortranm** [TASVideos/BizHawk#713]
[quote]*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.ApiHawk.ClientApi.OnRomLoaded()
   at BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args)
   at BizHawk.Client.EmuHawk.MainForm.OpenAdvancedMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)[/quote]
Every time I open a game with fbalpha_libretro.dll in version 1.11.7, an error with these texts show up.
I'm using Windows 10 x64.

[quote]*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.ApiHawk.ClientApi.OnRomLoaded()
   at BizHawk.Client.EmuHawk.MainForm.LoadRom(String path, LoadRomArgs args)
   at BizHawk.Client.EmuHawk.MainForm.RebootCore()
   at BizHawk.Client.EmuHawk.MainForm.StartNewMovie(IMovie movie, Boolean record)
   at BizHawk.Client.EmuHawk.RecordMovie.Ok_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)[/quote]
These show up when I try to record a movie.
Did I miss any dll files, or is this just how Libretro cores behave at the moment?

**Comment by zeromus** [comment]
libretro's been rewritten, all these kinds of bugs are out of date.
but please check the libretro compatibility page on the wiki (which is probably out of date now) to make sure this core is even supposed to work.
also i'll be improving libretro parts in the future to pack-in "whitelisted" dlls which are guaranteed to work approximately
