### ISSUE TITLE
Crash since support for detecting gamepad changes was added

### ISSUE THREAD

**Issue by aexoden** [TASVideos/BizHawk#722]
```
System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=Collection was modified; enumeration operation may not execute.
  Source=mscorlib
  StackTrace:
       at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
       at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
       at System.Collections.Generic.List`1.Enumerator.MoveNext()
       at BizHawk.Client.EmuHawk.GamePad360.UpdateAll() in D:\Software\BizHawk-git\BizHawk.Client.EmuHawk\Input\GamePad360.cs:line 99
       at BizHawk.Client.EmuHawk.Input.UpdateThreadProc() in D:\Software\BizHawk-git\BizHawk.Client.EmuHawk\Input\Input.cs:line 325
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

As far as I can tell, this is related to the recent (since 1.11.7) change to MainForm.cs which detects gamepad changes. If the timing is right, the Devices List could be changed during the loop. 

Either my system or gamepad is somewhat faulty and periodically disconnects and reconnects. The crash occurs rarely, often taking several hours of runtime before it occurs, and since most people wouldn't be connecting/disconnecting their gamepad often, it probably wouldn't come up.

**Comment by adelikat** [comment]
I think this will fix the exception, but I can't easily test of course :) Let me know if you still have issues
