### ISSUE TITLE
BizHawk crashes upon opening

### ISSUE THREAD

**Issue by Mario3264** [TASVideos/BizHawk#723]
`System.Exception: Initialization of Display Method failed; falling back to GDI+ ---> System.InvalidOperationException: Error compiling shader:  ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SlimDX.Utilities.BufferToString(ID3DXBuffer* buffer)
   at SlimDX.Direct3D9.ShaderBytecode.Compile(Byte[] sourceData, Macro[] defines, Include includeFile, String functionName, String profile, ShaderFlags flags, String& errors)
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9.CreateFragmentShader(Boolean cg, String source, String entry, Boolean required)
   --- End of inner exception stack trace ---
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9.CreateFragmentShader(Boolean cg, String source, String entry, Boolean required)
   at BizHawk.Bizware.BizwareGL.GuiRenderer..ctor(IGL owner)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
   --- End of inner exception stack trace ---`

**Comment by Mario3264** [comment]
Does not happen anymore.

**Comment by Mario3264** [comment]
It happens and BizHawk only opens properly when I press the "Copy" button on the crashlog window.

**Comment by Mario3264** [comment]
#527

**Comment by Mario3264** [comment]
#527 Bizhawk crashes on start

**Comment by Mario3264** [comment]
Solved by installing prereqs installer

**Comment by hehehahdd** [comment]
![Screenshot 2023-06-17 1 15 35 AM](https://github.com/TASEmulators/BizHawk/assets/134450827/e9797d5b-19f6-4091-94d3-15b2b347e8e7)
what the hell

**Comment by YoshiRulz** [comment]
Please direct RTC Vanguard questions to [their issue tracker](https://github.com/redscientistlabs/RTCV/issues). ~~And make a new issue instead of posting in an old, unrelated one next time.~~
