### ISSUE TITLE
I got this error when trying to play Bump 'N' Jump (1982-83) (Mattel) Intellivision

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#742]
System.ArgumentException: HLT is an unexpected behavior; Intellivision should run so long as the power is on.
   at BizHawk.Emulation.Cores.Components.CP1610.CP1610.Execute()
   at BizHawk.Emulation.Cores.Intellivision.Intellivision.FrameAdvance(Boolean render, Boolean rendersound)
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by alyosha-tas** [comment]
Hi,

Intellivision core currently does not have mapper support, so only games with the nominal rom size of 8kb will function at the moment. bump n Jump is a 32kb rom, so won't work. Mapper support is next after I get sound working, so look for it happening in the next month or so.

**Comment by alyosha-tas** [comment]
This game now runs correctly in the most recent dev build

**Comment by Cibomatto2002** [comment]
Thank you so much.
