### ISSUE TITLE
nes zapper broken

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#743]
as of latest code:
switch to neshawk, set P2 to zapper, reboot core, load duck hunt, and click:

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at BizHawk.Emulation.Cores.Nintendo.NES.PPU.LightGunCallback(Int32 x, Int32 y) in B:\git\bizhawk\BizHawk.Emulation.Cores\Consoles\Nintendo\NES\PPU.cs:line 122
   at BizHawk.Emulation.Cores.Nintendo.NES.Zapper.Read(IController c) in B:\git\bizhawk\BizHawk.Emulation.Cores\Consoles\Nintendo\NES\NESControllers.cs:line 577
   at BizHawk.Emulation.Cores.Nintendo.NES.NesDeck.ReadB(IController c) in B:\git\bizhawk\BizHawk.Emulation.Cores\Consoles\Nintendo\NES\NESControllers.cs:line 175
   at BizHawk.Emulation.Cores.Nintendo.NES.NES.read_joyport(Int32 addr) in B:\git\bizhawk\BizHawk.Emulation.Cores\Consoles\Nintendo\NES\NES.Core.cs:line 710
   at BizHawk.Emulation.Cores.Nintendo.NES.NES.ReadReg(Int32 addr) in B:\git\bizhawk\BizHawk.Emulation.Cores\Consoles\Nintendo\NES\NES.Core.cs:line 590
   at BizHawk.Emulation.Cores.Nintendo.NES.NES.ReadMemory(UInt16 addr) in B:\git\bizhawk\BizHawk.Emulation.Cores\Consoles\Nintendo\NES\NES.Core.cs:line 862
   at BizHawk.Emulation.Cores.Components.M6502.MOS6502X.Abs_READ_LDA() in B:\git\bizhawk\BizHawk.Emulation.Cores\CPUs\MOS 6502X\Execute.cs:line 1254
   at BizHawk.Emulation.Cores.Components.M6502.MOS6502X.ExecuteOneRetry() in B:\git\bizhawk\BizHawk.Emulation.Cores\CPUs\MOS 6502X\Execute.cs:line 2802
   at BizHawk.Emulation.Cores.Components.M6502.MOS6502X.ExecuteOne() in B:\git\bizhawk\BizHawk.Emulation.Cores\CPUs\MOS 6502X\Execute.cs:line 2981
   at BizHawk.Emulation.Cores.Nintendo.NES.NES.RunCpuOne() in B:\git\bizhawk\BizHawk.Emulation.Cores\Consoles\Nintendo\NES\NES.Core.cs:line 494
   at BizHawk.Emulation.Cores.Nintendo.NES.PPU.runppu(Int32 x) in B:\git\bizhawk\BizHawk.Emulation.Cores\Consoles\Nintendo\NES\PPU.cs:line 283
   at BizHawk.Emulation.Cores.Nintendo.NES.PPU.FrameAdvance() in B:\git\bizhawk\BizHawk.Emulation.Cores\Consoles\Nintendo\NES\PPU.run.cs:line 335
   at BizHawk.Emulation.Cores.Nintendo.NES.NES.FrameAdvance(Boolean render, Boolean rendersound) in B:\git\bizhawk\BizHawk.Emulation.Cores\Consoles\Nintendo\NES\NES.Core.cs:line 353
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force) in B:\git\bizhawk\BizHawk.Client.EmuHawk\MainForm.cs:line 2818
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop() in B:\git\bizhawk\BizHawk.Client.EmuHawk\MainForm.cs:line 523
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args) in B:\git\bizhawk\BizHawk.Client.EmuHawk\Program.cs:line 279

**Comment by alyosha-tas** [comment]
Forgot to check a disabled pixel condition, fixed now with  097bbee

**Comment by zeromus** [comment]
disabled pixels have some kind of color; we need to be checking that. just not checking it wrong by blowing the table (I changed the fix but forgot to refrerence the issue in the commit)
