### ISSUE TITLE
[Intellivision] I got this error when trying to play Chip Shot - Super Pro Golf (1987) (Intv Corp)

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#751]
I got this error when trying to play Chip Shot - Super Pro Golf (1987) (Intv Corp)

System.ArgumentException: HLT is an unexpected behavior; Intellivision should run so long as the power is on.
   at BizHawk.Emulation.Cores.Components.CP1610.CP1610.Execute()
   at BizHawk.Emulation.Cores.Intellivision.Intellivision.FrameAdvance(Boolean render, Boolean rendersound)
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by alyosha-tas** [comment]
Oops forgot to add it to the gamedb, should be fixed now
