### ISSUE TITLE
TAStudio ArgumentOutOfRangeException in StateToRemove

### ISSUE THREAD

**Issue by aji** [TASVideos/BizHawk#785]
Occasionally TAStudio will crash with the following exception:

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.SortedList`2.GetByIndex(Int32 index)
   at System.Collections.Generic.SortedList`2.ValueList.get_Item(Int32 index)
   at BizHawk.Client.Common.TasStateManager.StateToRemove()
   at BizHawk.Client.Common.TasStateManager.MaybeRemoveStates()
   at BizHawk.Client.Common.TasStateManager.SetState(Int32 frame, Byte[] state, Boolean skipRemoval)
   at BizHawk.Client.Common.TasStateManager.Capture(Boolean force)
   at BizHawk.Client.Common.TasMovie.GreenzoneCurrentFrame()
   at BizHawk.Client.Common.MovieSession.HandleMovieAfterFrameLoop()
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```

* BizHawk 1.11.9.1 (commit 3721e26)
* Windows 10 (running in VMware Fusion)

It seems to be caused by heavy use of branches. I'll try to find a reliable way to reproduce it. I've had this crash happen in a variety of circumstances, but Lua scripts seem to make it worse.

**Comment by aji** [comment]
Steps to reproduce:

1. Load any Genesis ROM
2. Open TAStudio
3. Create a branch
4. Run the following Lua script (a frame advance may be necessary to start it)

```lua
client.unpause()

for i = 1, 200 do
    emu.frameadvance()
end

savestate.saveslot(0)

for k = 1, 10 do
    for j = 1, 10 do
        savestate.loadslot(0)
        for i = 1, j do
            emu.frameadvance()
        end
    end
    savestate.saveslot(0)
end
	
client.pause()
```

I have had this happen in a variety of circumstances, not just pathological scripts like this one. However, this was the first simple script I could write that shows the crash. I will try again on the latest BizHawk.

**Comment by vadosnaprimer** [comment]
Nice catch, I was asking others if they're having this a couple weeks ago in tastudio thread. Thanks for the steps, will investigate asap.

**Comment by aji** [comment]
I found a much shorter Lua script that causes the crash:

```lua
client.unpause()
client.displaymessages(false)
while true do
    savestate.loadslot(0)
    emu.frameadvance()
    savestate.saveslot(0)
end
```

Interestingly, the crash only happens when advancing an odd number of frames between loading and saving. I think this might be related to the fact that TAStudio only puts a green frame every other frame. However, with an even number of frame advances, TAStudio still seems to end up with space for only 1 or 2 green frames.

**Comment by vadosnaprimer** [comment]
Reopen if you get that crash in a different way.
