### ISSUE TITLE
BizHawk Crashes when loading Save states.

### ISSUE THREAD

**Issue by Djavulen** [TASVideos/BizHawk#834]
System.ArgumentException: 1 is not a supported code page.
Parameter name: codepage
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(String name)
   at BizHawk.Client.Common.BinaryStateLoader.LoadAndDetect(String filename, Boolean isMovieLoad)
   at BizHawk.Client.Common.SavestateManager.LoadStateFile(String path, String name)
   at BizHawk.Client.EmuHawk.MainForm.LoadState(String path, String userFriendlyStateName, Boolean fromLua, Boolean supressOSD)
   at BizHawk.Client.EmuHawk.MainForm.LoadQuickSave(String quickSlotName, Boolean fromLua, Boolean supressOSD)
   at BizHawk.Client.EmuHawk.MainForm.CheckHotkey(String trigger)
   at BizHawk.Client.EmuHawk.MainForm.<ProcessInput>b__25(Boolean current, String trigger)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at BizHawk.Client.EmuHawk.MainForm.ProcessInput()
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

I get this error whenever i Load save states. 

BizHawk 1.12.1
Windows 10 (15063.250)

**Comment by jdpurcell** [comment]
You can try the latest build from here, it should be fixed: https://ci.appveyor.com/project/zeromus/bizhawk-udexo/build/artifacts

**Comment by Dep96** [comment]
still broken

**Comment by YoshiRulz** [comment]
@Dep96 This is a bug report from 1.x. If you're not using 1.x, please open a new issue. Either way, we can't fix it unless we know which exact version of BizHawk you're using, what game you're playing, and the contents of the savestate file (drag-and-drop into the comment box to upload).
