### ISSUE TITLE
Fails to load any GB ROM in SGB

### ISSUE THREAD

**Issue by Zaneclodon** [TASVideos/BizHawk#850]
As the title states, BizHawk will fail to load any Game Boy ROM in Super Game Boy.
Game Boy ROMs load fine when the "Load GB in SGB" option is not enabled, just obviously not in SGB.
I am using BizHawk version 1.12.2 on Windows 10 Home Edition version 1607.
A window will pop up with the below text when the ROM fails to load, and sometimes BizHawk will proceed to unload the ROM and display a black screen after hitting OK, but other times BizHawk will close upon hitting OK and a different window titled "Exception" with the same text and a copy option will appear. In both cases, the "Load GB in SGB" option is automatically disabled, but it can be re-enabled, reproducing the same results.
>System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.Common.Rewinder.Capture()
   at BizHawk.Client.EmuHawk.MainForm.CaptureRewind(Boolean suppressCaptureRewind)
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by hegyak** [comment]
I can confirm this issue.
The exact error message I get is:
A core accepted the rom, but threw an exception while loading it:

System.InvalidOperationException: Failed to load plugin C:\Users\*USERNAME*\AppData\Local\Temp\biz-21824-libsneshawk-32-compatibility-2c2821f3-8611-4dc6-88fa-f8007fc83fda.dll, error code: 0xC1
   at BizHawk.Common.InstanceDll..ctor(String dllPath)
   at BizHawk.Emulation.Cores.Nintendo.SNES.LibsnesApi..ctor(String dllPath)
   at BizHawk.Emulation.Cores.Nintendo.SNES.LibsnesCore..ctor(GameInfo game, Byte[] romData, Boolean deterministicEmulation, Byte[] xmlData, CoreComm comm, Object settings, Object syncSettings)
   at BizHawk.Client.Common.RomLoader.LoadRom(String path, CoreComm nextComm, Boolean forceAccurateCore, Int32 recursiveCount)

This is done by setting GB in SGB.  bSNES is set to compatibility mode as well.

**Comment by zeromus** [comment]
the bsnes core was in flux at this time. i'm sure it's been fixed by now in git.
