### ISSUE TITLE
Trace logger crashes with the Genesis

### ISSUE THREAD

**Issue by Ralakimus** [TASVideos/BizHawk#863]
"System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.<SetMemoryDomains>b__d(Int64 addr)
   at BizHawk.Emulation.Common.MemoryDomainDelegate.PeekByte(Int64 addr)
   at BizHawk.Emulation.Common.MemoryDomain.PeekUshort(Int64 addr, Boolean bigEndian)
   at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.<>c__DisplayClass9.<Disassemble>b__6(Int32 a)
   at BizHawk.Emulation.Cores.Components.M68000.MC68000.Disassemble(Int32 pc)
   at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.Disassemble(MemoryDomain m, UInt32 addr, Int32& length)
   at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.MakeTrace()
   at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.LibGPGX.gpgx_advance()
   at BizHawk.Emulation.Cores.Consoles.Sega.gpgx.GPGX.FrameAdvance(Boolean render, Boolean rendersound)
   at BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)"

**Comment by zeromus** [comment]
Trace logger crashes with the genesis when tracing which game at which scene? I'm 0 for 1 making it crash in shining force 2.

**Comment by Ralakimus** [comment]
Sonic 3 and Knuckles. It crashes at any time I attempt to start logging.
