### ISSUE TITLE
BizHawk 1.13.0 - AVI dump does not work at all, and exiting the emulator causes an unhandled exception error.

### ISSUE THREAD

**Issue by LarviStar** [TASVideos/BizHawk#873]
When I attempt to use the emulator's AVI writer to record video, I get a certain error like this: 

![image](https://user-images.githubusercontent.com/29338812/27004876-c37f7bbc-4ddf-11e7-88bd-24f5f98b8bc6.png)

I've attempted using "Cinepak Codec by Radius" and "Xvid MPEG-4 Codec" both giving me the same exact error as shown above.  AVI writing worked completely fine in 1.12.1 with these two codecs, and any of the other codecs installed on my OS.

Exiting the emulator will give me an unhandled exception, with an error titled "Object reference not set to an instance of an object." and give me these details: 

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9.FreePipeline(Pipeline pipeline)
   at BizHawk.Client.EmuHawk.Filters.RetroShaderChain.Dispose()
   at BizHawk.Client.EmuHawk.DisplayManager.Dispose()
   at BizHawk.Client.EmuHawk.MainForm.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at BizHawk.Client.EmuHawk.MainForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by zeromus** [comment]
Try recording an AVI for a game on a different system entirely

**Comment by nattthebear** [comment]
I've found the bug.  It will only happen if you choose to resize the video.  As a workaround for now, don't use the resize feature.

**Comment by nattthebear** [comment]
Fixed in 2.0
